(function () {
  const { data, breadcrumb } = window.App;
  const chapterId = new URLSearchParams(location.search).get("id");
  const chapter = data.findChapter(chapterId);
  const root = document.querySelector("#chapter-root");
  if (!chapter) {
    document.querySelector("#page-breadcrumb").innerHTML = breadcrumb([{ label: "History", href: "chapters.html?subject=history" }, { label: "Chapters" }]);
    root.innerHTML = `<div class="empty-state"><h1>Chapter not found</h1><p>Choose one of the five chapters in the Class 10 History course.</p><a class="button button-primary" href="chapters.html?subject=history">Browse History chapters</a></div>`;
    return;
  }

  const extra = chapter.enhanced || {};
  const completion = chapter.completion || {};
  const sectionNames = ["Introduction", "Learn in 5 minutes", "Story mode", "Main concepts", "Flowcharts", "Concept map", "Important people", "Important dates", "Detailed timeline", "Visual learning", "Causes and effects", "Comparison charts", "Memory tricks", "Don't confuse these", "Exam focus", "Quick revision", "Practice questions", "Answer writing", "Quiz", "Detailed concepts", "Important places", "People + place + event", "Important NCERT visuals", "Visual question practice", "Whole chapter flowchart", "Chapter in One Page", "Complete Chapter Revision Flow", "Complete Chapter Conclusion"];
  const sectionCount = sectionNames.length;
  const progressKey = `history-progress-${chapter.id}`;
  const getProgress = () => {
    try { return JSON.parse(localStorage.getItem(progressKey) || "[]"); } catch { return []; }
  };
  document.title = `${chapter.title} · Class 10 History`;
  document.querySelector("#page-breadcrumb").innerHTML = breadcrumb([{ label: chapter.subjectName, href: `chapters.html?subject=${encodeURIComponent(chapter.subjectId)}` }, { label: "Chapters", href: `chapters.html?subject=${encodeURIComponent(chapter.subjectId)}` }, { label: `Chapter ${chapter.number}` }]);

  const list = (items) => `<ul class="content-list">${items.map((item) => `<li>${item}</li>`).join("")}</ul>`;
  const comparisons = (items) => items.map((table) => `<div class="comparison-table-wrap" role="region" aria-label="${table.title}" tabindex="0"><table class="comparison-table"><caption>${table.title}</caption><thead><tr>${table.columns.map((column) => `<th scope="col">${column}</th>`).join("")}</tr></thead><tbody>${table.rows.map((row) => `<tr>${row.map((cell) => `<td>${cell}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`).join("");
  const confusionCards = (items) => `<div class="confusion-grid">${items.map((item) => `<article class="confusion-card"><div><strong>${item.left}</strong><span>vs</span><strong>${item.right}</strong></div><p>${item.difference}</p></article>`).join("")}</div>`;
  const flowcharts = (items) => items.map((flowchart) => flowchart.groups ? `<article class="flowchart flowchart-branch"><h3>${flowchart.title}</h3><div class="flow-branches">${flowchart.groups.map((group) => `<section class="flow-branch"><h4>${group.label}</h4>${group.items.map((item, index) => `${index ? '<div class="flow-connector" aria-hidden="true">↓</div>' : ""}<div class="flow-node">${item}</div>`).join("")}</section>`).join("")}</div></article>` : `<article class="flowchart flowchart-${flowchart.style}"><h3>${flowchart.title}</h3><ol>${flowchart.steps.map((step) => `<li>${step}</li>`).join("")}</ol></article>`).join("");
  const conceptMap = extra.conceptMap ? `<article class="concept-map"><div class="concept-root">${extra.conceptMap.center}</div><div class="concept-branches">${extra.conceptMap.branches.map((branch) => `<section class="concept-branch"><h3>${branch.label}</h3>${branch.items.map((item) => `<div class="concept-leaf">${item}</div>`).join("")}</section>`).join("")}</div></article>` : "";
  const timelineItems = data.timeline.filter((item) => item.chapterId === chapter.id && (!extra.timeline || item.topic)).sort((left, right) => Number((left.date.match(/\d+/) || [0])[0]) - Number((right.date.match(/\d+/) || [0])[0]));
  const timeline = `<div class="timeline-controls"><label class="toggle-field"><input type="checkbox" id="important-dates-only"><span>Show only important dates</span></label><span class="muted">${timelineItems.length} key moments</span></div><div class="timeline timeline-detailed" id="chapter-timeline">${timelineItems.map((item) => `<article class="timeline-item" data-important="${item.important ? "true" : "false"}"><div class="timeline-date">${item.date} ${item.important ? '<span class="badge badge-important">Key date</span>' : ""}</div><h3>${item.event}</h3><p>${item.description}</p><span class="badge">${item.topic || item.chapterTitle}</span></article>`).join("")}</div>`;
  const exam = extra.exam || { remember: [], concepts: [], dates: [], names: [], differences: [], short: "", long: "" };
  const quick = extra.quick || { tenSeconds: chapter.summary, oneMinute: chapter.oneMinute, fiveMinutes: chapter.fiveMinutes, detailed: chapter.summary };
  const existingQuestions = data.questionBank.filter((item) => item.chapterId === chapter.id);
  const shortQuestions = [exam.short, ...existingQuestions.filter((item) => item.type === "Short Answer").map((item) => item.question)].filter(Boolean);
  const longQuestions = [exam.long, ...existingQuestions.filter((item) => item.type === "Long Answer").map((item) => item.question)].filter(Boolean);
  const completed = getProgress();
  const percent = Math.round(completed.length / sectionCount * 100);

  const renderWholeFlow = (items) => `<article class="whole-flowchart"><p class="flowchart-note">Revise this flowchart before the exam to recall the complete chapter.</p><div class="whole-flow-steps">${items.map((phase, index) => `<section class="whole-flow-phase"><span class="whole-flow-number">${String(index + 1).padStart(2, "0")}</span><div><h3>${phase.title}</h3><ul>${phase.points.map((point) => `<li>${point}</li>`).join("")}</ul></div></section>`).join('<div class="whole-flow-arrow" aria-hidden="true">↓</div>')}</div></article>`;
  const renderVisualArt = (visual) => {
    if (visual.imageSrc) return `<figure class="provided-visual chapter-visual"><img src="${visual.imageSrc}" alt="${visual.alt || `${visual.title}. ${visual.shows}`}" width="${visual.imageWidth}" height="${visual.imageHeight}" loading="lazy"><div class="provided-image-missing" hidden role="status">The supplied image file is not available in the workspace yet. Add the unchanged image as <strong>${visual.imageSrc}</strong>.</div></figure>`;
    const icon = { allegory: "fa-person-dress", assembly: "fa-people-roof", map: "fa-route", route: "fa-person-walking", symbol: "fa-cube", meeting: "fa-people-group", network: "fa-share-nodes", exchange: "fa-earth-americas", routes: "fa-ship", machine: "fa-gears", loom: "fa-grip", factory: "fa-industry", press: "fa-print", newspaper: "fa-newspaper" }[visual.kind] || "fa-landmark";
    const labels = visual.diagramLabels || (visual.kind === "allegory" ? ["Marianne · France", "Germania · Germany"] : visual.kind === "machine" ? ["Several spindles", "One spinning worker", "More thread"] : visual.kind === "loom" ? ["Shuttle", "Warp threads", "Faster weaving"] : visual.kind === "press" ? ["Arrange type", "Ink the form", "Press many copies"] : visual.kind === "newspaper" ? ["Printed report", "Readers share", "Public debate"] : visual.kind === "exchange" ? ["Americas", "Crops · disease", "Other regions"] : visual.kind === "route" ? ["Sabarmati", "March", "Dandi"] : visual.kind === "network" ? ["East Asia", "Trade routes", "Europe · Africa"] : visual.kind === "routes" ? ["Recruitment", "Ocean crossing", "Plantation work"] : visual.kind === "factory" ? ["Household work", "Merchant network", "Factory floor"] : visual.kind === "symbol" ? ["Salt", "Colonial rule", "Public protest"] : visual.kind === "assembly" ? ["Elected delegates", "Constitution", "Crown refused"] : ["People", "Shared campaign", "Different aims"]);
    const graphic = visual.diagramGroups ? `<div class="visual-map-branches">${visual.diagramGroups.map((group) => `<section><strong>${group.title}</strong>${group.items.map((item) => `<span>${item}</span>`).join("")}</section>`).join("")}</div>` : `<div class="visual-recreation-flow">${labels.map((label, index) => `<span>${label}</span>${index < labels.length - 1 ? '<i class="fa-solid fa-arrow-right" aria-hidden="true"></i>' : ""}`).join("")}</div>`;
    return `<div class="visual-recreation visual-${visual.kind}" role="img" aria-label="Original educational diagram: ${visual.title}. ${visual.shows}"><div class="visual-recreation-mark"><i class="fa-solid ${icon}" aria-hidden="true"></i></div>${graphic}</div>`;
  };
  const renderVisualCard = (visual) => `<article class="chapter-visual-card"><div class="chapter-visual-art">${renderVisualArt(visual)}</div><div class="chapter-visual-copy"><div class="eyebrow">Source study · ${visual.kind}</div><h3>${visual.title}</h3><p><strong>What is this?</strong> ${visual.what}</p>${visual.associatedWith ? `<p><strong>Associated with:</strong> ${visual.associatedWith}</p>` : ""}${visual.represents ? `<p><strong>Represents:</strong> ${visual.represents}</p>` : ""}${visual.elements ? `<p><strong>Important visual elements:</strong> ${visual.elements}</p>` : ""}${visual.chapterConnection ? `<p><strong>Chapter connection:</strong> ${visual.chapterConnection}</p>` : ""}<p><strong>What does it show?</strong> ${visual.shows}</p><p><strong>Why is it important?</strong> ${visual.importance}</p>${visual.examFocus ? `<div class="place-exam-point"><strong>Exam focus</strong><span>${visual.examFocus}</span></div>` : ""}<div class="visual-remember"><strong>Remember</strong><ul>${visual.remember.map((point) => `<li>${point}</li>`).join("")}</ul>${visual.memoryLine ? `<p class="visual-memory-line">${visual.memoryLine}</p>` : ""}</div></div></article>`;
  const renderVisuals = (items) => {
    const comparisonGroup = items.filter((item) => item.comparisonGroup === "European national allegories");
    const remaining = items.filter((item) => item.comparisonGroup !== "European national allegories");
    const pair = comparisonGroup.length ? `<div class="chapter-visual-pair">${comparisonGroup.map(renderVisualCard).join("")}</div><div class="allegory-comparison-wrap" role="region" aria-label="Marianne and Germania comparison" tabindex="0"><table class="comparison-table"><caption>Marianne and Germania at a glance</caption><thead><tr><th scope="col">Visual</th><th scope="col">Represents</th><th scope="col">Country</th><th scope="col">Main idea</th></tr></thead><tbody><tr><th scope="row">Marianne</th><td>French nation</td><td>France</td><td>Liberty / Republic / National identity</td></tr><tr><th scope="row">Germania</th><td>German nation</td><td>Germany</td><td>Unity / German nation</td></tr></tbody></table><p class="allegory-memory-line"><strong>Marianne → France</strong><strong>Germania → Germany</strong></p></div>` : "";
    return `${pair}<div class="chapter-visual-grid">${remaining.map(renderVisualCard).join("")}</div>`;
  };
  const renderPlaces = (items) => `<div class="important-place-grid">${items.map((place) => `<article class="important-place-card"><div class="place-card-top"><i class="fa-solid fa-location-dot" aria-hidden="true"></i><div><h3>${place.name}</h3><span>${place.location}</span></div></div><p><strong>Connection</strong> ${place.connection}</p><p><strong>Historical significance</strong> ${place.significance}</p><div class="place-exam-point"><strong>Exam point</strong><span>${place.exam}</span></div></article>`).join("")}</div>`;
  const renderPeopleConnections = (items) => `<div class="people-place-grid">${items.map((item) => `<article class="people-place-card"><h3>${item.person}</h3><div class="connection-chain"><span><small>PLACE</small>${item.place}</span><i class="fa-solid fa-arrow-down" aria-hidden="true"></i><span><small>EVENT</small>${item.event}</span><i class="fa-solid fa-arrow-down" aria-hidden="true"></i><span><small>CONTRIBUTION</small>${item.contribution}</span><i class="fa-solid fa-arrow-down" aria-hidden="true"></i><span><small>RESULT / IMPACT</small>${item.impact}</span></div></article>`).join("")}</div>`;
  const renderMemorySheet = (sheet, chapter) => `<div class="memory-sheet"><header><div class="eyebrow">Last-minute revision</div><h3>Chapter in One Page · ${chapter.title}</h3></header><div class="memory-sheet-grid"><article><h4>Important people</h4><ul>${sheet.people.map((item) => `<li>${item}</li>`).join("")}</ul></article><article><h4>Important dates</h4><ul>${sheet.dates.map((item) => `<li>${item}</li>`).join("")}</ul></article><article><h4>Important places</h4><ul>${sheet.places.map((item) => `<li>${item}</li>`).join("")}</ul></article><article><h4>Important terms</h4><ul>${sheet.terms.map((item) => `<li>${item}</li>`).join("")}</ul></article><article><h4>Important causes</h4><ul>${sheet.causes.map((item) => `<li>${item}</li>`).join("")}</ul></article><article><h4>Important effects</h4><ul>${sheet.effects.map((item) => `<li>${item}</li>`).join("")}</ul></article><article><h4>Important differences</h4><ul>${sheet.differences.map((item) => `<li>${item}</li>`).join("")}</ul></article><article class="must-remember"><h4>Must remember</h4><ol>${sheet.mustRemember.map((item) => `<li>${item}</li>`).join("")}</ol></article></div></div>`;

  const content = [
    `<p>${chapter.overview}</p><div class="chapter-intro-strip"><div class="intro-stat"><strong>${timelineItems.length}</strong><span>dated moments</span></div><div class="intro-stat"><strong>${chapter.people.length}</strong><span>key personalities</span></div><div class="intro-stat"><strong>${extra.concepts?.length || 0}</strong><span>core concepts</span></div></div><div class="chapter-progress"><div class="progress-label"><strong>Your chapter progress</strong><span id="chapter-progress-label">${percent}% complete</span></div><div class="progress-track"><div id="chapter-progress-fill" class="progress-fill" style="width:${percent}%"></div></div><p>Mark sections as studied. Progress is saved on this device.</p></div>`,
    `<div class="quick-lead"><span class="quick-time">5 min</span><p>${chapter.fiveMinutes}</p></div><div class="topic-list">${chapter.topics.map((topic) => `<span class="topic-pill">${topic}</span>`).join("")}</div>`,
    `<ol class="story-list">${chapter.story.map((step) => `<li>${step}</li>`).join("")}</ol>`,
    `<div class="concept-grid">${(extra.concepts || []).map((item) => `<article class="concept-card"><div class="eyebrow">Core idea</div><h3>${item.title}</h3><p>${item.text}</p><div class="concept-example"><strong>Example</strong><p>${item.example}</p></div></article>`).join("")}</div>`,
    flowcharts(extra.flowcharts || [{ title: chapter.visual.label, style: "horizontal", steps: chapter.visual.points }]),
    conceptMap,
    list(chapter.people),
    list(chapter.dates),
    timeline,
    `<div class="visual-learning-grid"><article class="visual-learning-item"><span class="visual-icon"><i class="fa-solid fa-map-location-dot" aria-hidden="true"></i></span><div><h3>Place and context</h3><p>Connect each development to its places and regions using the dated timeline.</p></div></article><article class="visual-learning-item"><span class="visual-icon"><i class="fa-solid fa-people-group" aria-hidden="true"></i></span><div><h3>People and movements</h3><p>Relate each personality's contribution to a movement, institution, or community.</p></div></article><article class="visual-learning-item"><span class="visual-icon"><i class="fa-solid fa-arrow-right-arrow-left" aria-hidden="true"></i></span><div><h3>Read the relationships</h3><p>Trace causes and outcomes in the flowcharts, then compare how historical paths differed.</p></div></article></div><figure class="historical-placeholder" role="img" aria-label="Illustrated placeholder for a properly licensed historical image related to ${chapter.title}"><div class="placeholder-mark"><i class="fa-regular fa-image" aria-hidden="true"></i></div><figcaption><strong>Licensed image slot</strong><span>A public-domain or correctly licensed image related to ${chapter.topics[0]} can be added here.</span></figcaption></figure>`,
    `<h3>Trace the relationship</h3>${list(chapter.causesEffects)}`,
    comparisons(extra.comparisons || []),
    `<div class="memory-grid">${(extra.memory || [chapter.mnemonics]).map((trick, index) => `<article class="memory-card"><span class="memory-number">${String(index + 1).padStart(2, "0")}</span><p>${trick}</p></article>`).join("")}</div>`,
    confusionCards(extra.confusion || []),
    `<div class="exam-focus-grid"><article class="exam-focus-card"><h3><i class="fa-solid fa-star" aria-hidden="true"></i> Must remember</h3>${list(exam.remember)}</article><article class="exam-focus-card"><h3><i class="fa-solid fa-bullseye" aria-hidden="true"></i> Important concepts</h3>${list(exam.concepts)}</article><article class="exam-focus-card"><h3><i class="fa-regular fa-calendar" aria-hidden="true"></i> High-priority dates</h3>${list(exam.dates)}</article><article class="exam-focus-card"><h3><i class="fa-solid fa-user" aria-hidden="true"></i> People and roles</h3>${list(exam.names)}</article><article class="exam-focus-card"><h3><i class="fa-solid fa-scale-balanced" aria-hidden="true"></i> Important differences</h3>${list(exam.differences)}</article><article class="exam-focus-card"><h3><i class="fa-solid fa-pen" aria-hidden="true"></i> 3-mark focus</h3><p>${exam.short}</p><h3>5-mark focus</h3><p>${exam.long}</p></article></div><p class="muted exam-note">These are high-priority revision topics, not predictions about an examination.</p>`,
    `<div class="revision-levels"><article class="revision-level revision-10"><span>10 seconds</span><p>${quick.tenSeconds}</p></article><article class="revision-level revision-1"><span>1 minute</span>${list(quick.oneMinute)}</article><article class="revision-level revision-5"><span>5 minutes</span><p>${quick.fiveMinutes}</p></article><article class="revision-level revision-detailed"><span>Detailed revision</span><p>${quick.detailed}</p><a class="button button-outline button-small" href="revision.html?chapter=${encodeURIComponent(chapter.id)}">Open revision cards</a></article></div><div class="visual-summary"><div class="eyebrow">One-page refresher</div><h3>Visual summary</h3><div class="visual-summary-grid"><article><strong>DATES</strong><p>${exam.dates.slice(0, 4).join(" · ")}</p></article><article><strong>PEOPLE</strong><p>${exam.names.slice(0, 3).join(" · ")}</p></article><article><strong>EVENTS</strong><p>${chapter.events.slice(0, 3).map((item) => item.split(":")[0]).join(" · ")}</p></article><article><strong>CAUSE → EFFECT</strong><p>${chapter.causesEffects[0]}</p></article><article><strong>KEY TERMS</strong><p>${chapter.terms.slice(0, 4).map((item) => item.split(":")[0]).join(" · ")}</p></article></div></div>`,
    `<h3>3-mark questions</h3><p>Usually cover three distinct, relevant points and add evidence where useful.</p>${list(shortQuestions)}<h3>5-mark questions</h3><p>Build a supported explanation with several points and a short conclusion.</p>${list(longQuestions)}<h3>Case-based practice</h3>${list(existingQuestions.filter((item) => item.type === "Case-based" || item.type === "Case Based").map((item) => item.question))}<a class="button button-outline" href="questions.html?chapter=${encodeURIComponent(chapter.id)}">Browse question bank <i class="fa-solid fa-arrow-right" aria-hidden="true"></i></a>`,
    `<div class="answer-framework"><h3>3 marks: build three clear points</h3><ol><li>Answer the question directly.</li><li>Add two relevant facts or examples.</li><li>Connect your evidence to the question.</li></ol></div><div class="answer-framework"><h3>5 marks: develop a supported explanation</h3><ol><li>Give a short introduction that sets the context.</li><li>Develop three to four distinct, sequenced points.</li><li>Support your points with an example, date, or evidence.</li><li>Explain the outcome and conclude.</li></ol></div>`,
    `<div id="chapter-quiz"></div>`,
    `<div class="detailed-concepts">${(completion.visuals || []).map((visual) => `<article><h3>${visual.title}</h3><p>${visual.shows} ${visual.importance}</p></article>`).join("")}</div>`,
    renderPlaces(completion.places || []),
    renderPeopleConnections(completion.peoplePlaces || []),
    `<div class="visual-section-intro"><p>These are original educational recreations and source-reading diagrams, not reproduced NCERT pages. Study the caption and evidence, then interpret the historical idea.</p></div>${renderVisuals(completion.visuals || [])}`,
    `<div class="visual-question-grid">${(completion.visuals || []).flatMap((visual) => visual.questions.map((question) => `<article class="visual-question-card"><span class="badge">${visual.title}</span><h3>${question}</h3><details><summary>What to look for</summary><p>${visual.shows} ${visual.importance}</p></details></article>`)).join("")}</div>`,
    renderWholeFlow(completion.wholeFlow || []),
    renderMemorySheet(completion.memorySheet || { people: [], dates: [], places: [], terms: [], causes: [], effects: [], differences: [], mustRemember: [] }, chapter),
    `<div class="revision-chain" aria-label="Complete chapter revision flow">${(completion.memorySheet?.chain || []).map((step, index) => `<span>${step}</span>${index < completion.memorySheet.chain.length - 1 ? '<i class="fa-solid fa-arrow-right" aria-hidden="true"></i>' : ""}`).join("")}</div><p class="muted">Read the chain from left to right, then explain the links in your own words.</p>`,
    `<div class="complete-conclusion">${(completion.conclusion?.paragraphs || []).map((paragraph) => `<p>${paragraph}</p>`).join("")}<div class="conclusion-takeaways"><h3>Board-exam recall points</h3><ul>${(completion.conclusion?.takeaways || []).map((point) => `<li>${point}</li>`).join("")}</ul></div></div>`
  ];

  const nav = sectionNames.map((name, index) => `<a href="#section-${index}">${name}</a>`).join("");
  const sections = content.map((html, index) => `<section class="study-section" id="section-${index}"><div class="study-section-heading"><h2>${index + 1}. ${sectionNames[index]}</h2><button class="section-complete${completed.includes(index) ? " is-complete" : ""}" type="button" data-complete-section="${index}" aria-pressed="${completed.includes(index)}"><i class="fa-solid fa-check" aria-hidden="true"></i><span>${completed.includes(index) ? "Studied" : "Mark studied"}</span></button></div>${html}</section>`).join("");
  root.innerHTML = `<header class="page-intro"><div class="eyebrow">${chapter.subjectName} · Chapter ${chapter.number}</div><h1>${chapter.title}</h1><p>${chapter.description}</p><div class="hero-actions" style="margin-top:18px"><a class="button button-outline button-small" href="chapters.html?subject=${encodeURIComponent(chapter.subjectId)}"><i class="fa-solid fa-arrow-left" aria-hidden="true"></i> All chapters</a><button class="button button-coral button-small" id="understand-toggle" type="button" aria-expanded="false" aria-controls="simple-explanation"><i class="fa-regular fa-face-sad-tear" aria-hidden="true"></i> I Don't Understand This</button></div><div class="simple-panel" id="simple-explanation" hidden><h3>Let's make it simple</h3>${["WHAT HAPPENED?", "WHY DID IT HAPPEN?", "WHO WAS INVOLVED?", "WHAT HAPPENED NEXT?", "WHY IS IT IMPORTANT?"].map((label, index) => `<div class="simple-item"><strong>${label}</strong><p>${chapter.simple[index]}</p></div>`).join("")}</div></header><div class="study-layout"><nav class="study-sidebar" aria-label="On this page"><strong>In this chapter</strong>${nav}</nav><div class="study-content">${sections}</div></div>`;
  root.querySelectorAll(".provided-visual img").forEach((image) => image.addEventListener("error", () => {
    image.hidden = true;
    image.nextElementSibling.hidden = false;
  }));

  document.querySelector("#understand-toggle").addEventListener("click", (event) => {
    const panel = document.querySelector("#simple-explanation");
    const expanded = event.currentTarget.getAttribute("aria-expanded") === "true";
    event.currentTarget.setAttribute("aria-expanded", String(!expanded));
    panel.hidden = expanded;
  });
  document.querySelectorAll("[data-complete-section]").forEach((button) => button.addEventListener("click", () => {
    const selected = Number(button.dataset.completeSection);
    const progress = new Set(getProgress());
    if (progress.has(selected)) progress.delete(selected);
    else progress.add(selected);
    const saved = [...progress].sort((left, right) => left - right);
    localStorage.setItem(progressKey, JSON.stringify(saved));
    const completion = Math.round(saved.length / sectionCount * 100);
    document.querySelector("#chapter-progress-label").textContent = `${completion}% complete`;
    document.querySelector("#chapter-progress-fill").style.width = `${completion}%`;
    button.classList.toggle("is-complete", progress.has(selected));
    button.setAttribute("aria-pressed", String(progress.has(selected)));
    button.querySelector("span").textContent = progress.has(selected) ? "Studied" : "Mark studied";
  }));
  document.querySelector("#important-dates-only").addEventListener("change", (event) => {
    document.querySelectorAll("#chapter-timeline .timeline-item").forEach((item) => {
      item.hidden = event.target.checked && item.dataset.important !== "true";
    });
  });
  window.QuizController.mount(document.querySelector("#chapter-quiz"), data.quiz[chapter.id] || [], { compact: true, title: `Chapter ${chapter.number} check-in` });
})();