(function () {
  const subject = window.LEARNING_DATA.findSubject("economics");
  const chapters = [
    {
      id: "economics-1", number: 1, title: "Development",
      description: "Compare how people define a better life, measure progress, and balance income with health, education, equality, and sustainability.",
      topics: ["Different development goals", "Income and comparison", "Public facilities", "Sustainable development"],
      overview: "Development means improving people's lives, but people can value different things. Income matters, yet health, education, security, equality, freedom, and a safe environment matter too. This chapter compares development goals and ways of measuring progress.",
      fiveMinutes: "People have different development goals: a worker may want fair wages, a student quality education, and a community clean water. Average income (per capita income) helps compare countries, but can hide inequality and cannot show health or schooling. The Human Development approach adds health and education indicators. Public facilities such as schools, clinics, and sanitation serve whole communities. Development today must also protect resources for the future.",
      topics: ["Development goals", "Per capita income", "Human Development Index", "Public facilities", "Sustainability"],
      people: ["Amartya Sen: economist whose work highlights capabilities and human development.", "Residents and workers: people whose differing priorities show that development goals are not identical.", "Future generations: stakeholders whose needs matter when using limited natural resources."],
      dates: ["1990: UNDP begins publishing the Human Development Report.", "2000: UN member states adopt the Millennium Development Goals.", "2015: Sustainable Development Goals are adopted by UN member states."],
      events: ["Different goals: people may value income, respect, security, equality, and freedom differently.", "Per capita income: total income divided by population gives an average, not a picture of distribution.", "Human Development comparison: health and education indicators complement income.", "Public facilities: collective services such as schools and health centres improve quality of life.", "Resource pressure: groundwater depletion and pollution show costs of unsustainable growth."],
      terms: ["Per capita income: average income per person, found by dividing total income by population.", "National income: the total value of income earned in a country over a period.", "Infant mortality rate: deaths of children under one year of age per 1,000 live births in a year.", "Literacy rate: share of people aged seven and above who can read and write with understanding.", "Sustainable development: meeting present needs while preserving the ability of future generations to meet theirs."],
      causesEffects: ["Cause: people value different things. Effect: one income measure cannot define development for everyone.", "Cause: income averages hide who receives earnings. Effect: two places with equal averages may have very different inequality.", "Cause: overuse of groundwater and fossil fuels. Effect: resources become harder to replace and future choices shrink."],
      mnemonics: "Compare progress with H-I-E: Health, Income, Education; then ask who benefits and whether it lasts.",
      visual: { label: "A fuller measure of development", kind: "route", points: ["Income and work", "Health and education", "Equality and security", "A sustainable future"] },
      story: ["A family asks what would make life better; its answers are not limited to a higher wage.", "Different people name different goals, and some goals can conflict.", "Economists compare income averages, then notice what those averages leave out.", "Health, schooling, and public facilities add a more human picture of progress.", "Sustainable choices consider people today and people who will live in the future."],
      simple: ["Development means making people's lives better, and people may want different things.", "Income helps, but an average cannot show whether money is shared fairly.", "Health, education, safety, respect, and a clean environment matter too.", "Schools, clinics, and clean water are public facilities that help communities.", "Using resources carefully helps people in the future meet their needs."],
      simple: ["Development means making life better, but people do not all want the same things.", "Income is useful, but an average cannot tell us whether money is shared fairly.", "Health, education, safety, equality, and respect also affect people's lives.", "Public services help many people at once, including those with low incomes.", "Using resources carefully helps future generations meet their needs too."],
      summary: "Development is multidimensional. Income comparisons help, but they need to be read alongside distribution, health, education, public facilities, and environmental sustainability.",
      oneMinute: ["Different people can have different development goals.", "Per capita income is an average and can hide unequal distribution.", "Health and education measures add information beyond income.", "Public facilities and sustainable resource use matter to quality of life."],
      assertionReasons: [
        ["Average income alone cannot show how equally income is shared.", "An average combines all incomes into one figure."],
        ["Public facilities can improve development for many people at once.", "Schools and health centres provide services to a community."],
        ["Two countries with similar per capita income may have different quality of life.", "Income does not directly measure health, education, or distribution."],
        ["Sustainable development considers future generations.", "Some natural resources are limited or take a long time to replenish."],
        ["People may disagree about which development goal is most important.", "People live in different circumstances and have different priorities."],
        ["Literacy rate is a social indicator.", "It measures the share of people aged seven and above able to read and write with understanding."],
        ["Infant mortality rate is used as an indicator of health.", "It records deaths under age one per 1,000 live births in a year."],
        ["A rise in national income guarantees that every person is better off.", "National income is a total and does not show how its gains are distributed."],
        ["Overuse of groundwater can threaten future development.", "Groundwater recharge may be slower than the rate at which water is withdrawn."],
        ["Development includes more than material possessions.", "People also value security, respect, freedom, and a clean environment."]
      ],
      completion: {
        conclusion: { paragraphs: ["This chapter asks a simple but important question: what does development mean, and for whom? A higher income can improve access to food, housing, and choices, but different people may have different goals. A landless worker may want stable work and fair wages, while a student may prioritise education and a community may need clean water.", "Per capita income is useful for comparing average income between countries, but it hides differences within each country. It also says little about health, schooling, or public services. Human Development comparisons therefore include indicators such as life expectancy, literacy, and schooling alongside income. Public facilities matter because health care, education, sanitation, and safe water benefit communities broadly.", "Finally, development must be sustainable. Groundwater, forests, and fossil fuels can be depleted or damaged when present use exceeds what nature can replace. The key exam lesson is to compare more than one indicator, explain who benefits, and consider whether improvements can continue without harming future generations."], takeaways: ["Development goals differ between people and groups.", "Per capita income is an average, not a distribution measure.", "Health and education indicators complement income.", "Public facilities improve community well-being.", "Sustainability protects options for future generations."] },
        wholeFlow: [{title:"START · What does a better life mean?",points:["People have different goals and priorities","Goals may complement or conflict with one another"]},{title:"MEASURE · Income",points:["National income totals earnings","Per capita income = national income ÷ population","An average can hide inequality"]},{title:"LOOK BEYOND INCOME",points:["Health: life expectancy and infant mortality","Education: literacy and schooling","Public facilities: clinics, schools, water, sanitation"]},{title:"COMPARE FAIRLY",points:["Check who receives income","Compare more than one social indicator","Ask whether services are accessible"]},{title:"THINK AHEAD · Sustainability",points:["Natural resources are not all unlimited","Overuse and pollution reduce future choices","Meet present needs while protecting future needs"]},{title:"CONCLUSION",points:["Development is multidimensional","Measure income, people’s capabilities, distribution, and sustainability"]}],
        visuals:[{kind:"network",title:"Development is more than income",what:"A concept map joining income with human and environmental measures.",shows:"Income connects to health, education, equality, public facilities, and sustainability.",importance:"It prevents a single average from being mistaken for a complete picture of people's lives.",remember:["Income matters but is not the only goal.","Check distribution and public services.","Consider future generations."],questions:["Why is per capita income not a complete measure of development?","Name two non-income indicators of development."],source:"Chapter concept map."},{kind:"map",title:"Compare indicators, not just averages",what:"A comparison framework for reading country development data.",shows:"Income, life expectancy, literacy, schooling, and public services provide different information.",importance:"A fair comparison explains what each indicator can and cannot tell us.",remember:["An average hides distribution.","Health and education add context.","Use indicators together."],questions:["What can infant mortality tell us that average income cannot?","Why compare literacy alongside income?"],source:"Indicator guide."}],
        places:[{name:"Kerala",location:"India",connection:"Public investment in health and education",significance:"Kerala is commonly used in the chapter's development comparisons to discuss strong social indicators relative to income.",exam:"Explain why social indicators can tell a different story from income alone."},{name:"Sri Lanka",location:"South Asia",connection:"Health and education indicators",significance:"The country is used in development comparisons to illustrate that social outcomes should be considered alongside income.",exam:"Compare social indicators rather than assuming income alone settles the comparison."}],
        peoplePlaces:[{person:"Amartya Sen",place:"India and international development research",event:"Human development and capabilities approach",contribution:"Emphasised people's capabilities and freedoms, not income alone.",impact:"Supports a broader understanding of development."}],
        memorySheet:{terms:["Per capita income → average income per person.","Literacy rate → share able to read and write with understanding.","Infant mortality → deaths under one per 1,000 live births.","Sustainable development → progress that protects future needs."],causes:["Different goals → development needs more than one measure.","Unequal incomes → averages can hide who benefits.","Resource overuse → future choices can shrink."],effects:["Public facilities → wider access to essential services.","Education and health measures → fuller comparison of well-being.","Sustainable use → resources remain available longer."],differences:["National income is a total; per capita income is an average.","Income is material; development also includes social and environmental goals."],chain:["Different goals","Income measure","Distribution check","Health and education","Public facilities","Sustainability","Human well-being"]}
      }
    },
    {
      id: "economics-2", number: 2, title: "Sectors of the Indian Economy",
      description: "Understand primary, secondary, and tertiary work, employment, underemployment, public services, and how the sectors depend on one another.",
      topics: ["Primary, secondary, tertiary sectors", "GDP", "Underemployment", "Organised and unorganised work", "Public sector"],
      overview: "Economic activities can be grouped by what they produce: primary activities use natural resources, secondary activities process materials, and tertiary activities provide services. The sectors depend on one another. This chapter also examines GDP, employment, underemployment, work conditions, and the roles of public and private sectors.",
      fiveMinutes: "Farming, fishing, and mining belong to the primary sector; manufacturing and construction to the secondary; transport, banking, and teaching to the tertiary. GDP adds the value of final goods and services produced within a country in a year. A sector can contribute to output without providing enough secure jobs: disguised unemployment occurs when more people work than needed. The organised sector follows rules and offers more formal protections; the unorganised sector often lacks them. Government activity can provide essential services and support public welfare.",
      people: ["Workers and farmers: producers whose work may be seasonal, insecure, or underpaid.", "Government: provider of public services and regulator of working conditions.", "Consumers: people whose demand links production, trade, and services."],
      dates: ["1950: Planning Commission established in India.", "1991: major economic reforms begin in India.", "2005: National Rural Employment Guarantee Act is enacted."],
      events: ["Sector grouping: activities are classified by whether they extract, process, or provide services.", "GDP calculation: only final goods and services are counted to avoid double counting.", "Underemployment: people are working, but fewer workers could produce the same output.", "Employment guarantee: public employment programmes aim to provide wage work and rural assets.", "Sector interdependence: services support production while production creates demand for services."],
      terms: ["Primary sector: activities using natural resources, such as farming, fishing, and mining.", "Secondary sector: activities that process raw materials into manufactured goods or construction.", "Tertiary sector: services such as transport, banking, health, and education.", "GDP: value of final goods and services produced within a country during a year.", "Disguised unemployment: more people are engaged in work than are needed, so some can leave without reducing output."],
      causesEffects: ["Cause: seasonal or limited rural work. Effect: workers may remain employed but underuse their labour.", "Cause: counting intermediate goods repeatedly. Effect: GDP would be overstated; count final value instead.", "Cause: weak legal protection and irregular work. Effect: unorganised workers face greater insecurity."],
      mnemonics: "P-S-T = Pull from nature, Shape materials, Provide services.",
      visual: { label: "How sectors depend on one another", kind: "route", points: ["Primary resources", "Secondary processing", "Tertiary services", "Household and market demand"] },
      story: ["A farmer grows cotton, but a crop alone does not explain the whole economy.", "A factory turns cotton into cloth, and transport carries it to a shop.", "Banking, storage, communication, and retail services help the product reach buyers.", "GDP helps measure final production, while employment data reveal who has secure work.", "The chapter asks not only what an economy produces, but also whether people benefit from decent work and public services."],
      simple: ["The primary sector gets or grows things from nature.", "The secondary sector makes products or builds things.", "The tertiary sector provides services such as transport, banking, and teaching.", "Underemployment means people's work time or ability is not fully used.", "The sectors depend on each other, and public services support people's lives."],
      simple: ["The primary sector takes or grows things from nature.", "The secondary sector makes or builds products from materials.", "The tertiary sector provides useful services to people and businesses.", "Underemployment means someone has work, but their time or skill is not fully used.", "The government can provide services and support jobs that markets do not provide fairly."],
      summary: "The three sectors are connected through production and services. GDP measures final output, but employment quality and underemployment reveal whether growth creates adequate livelihoods. Public and private activity both shape the economy.",
      oneMinute: ["Primary = natural resources; secondary = processing; tertiary = services.", "GDP counts final goods and services to avoid double counting.", "Disguised unemployment means some workers can leave without reducing output.", "Organised work has formal rules; unorganised work often lacks protections."],
      assertionReasons: [
        ["The value of final goods is used in GDP calculation.", "Counting intermediate goods again would double count their value."],
        ["The tertiary sector supports the primary and secondary sectors.", "Transport, banking, and communication help production and trade."],
        ["Disguised unemployment can exist even when everyone appears to be working.", "Some workers can leave without reducing total output."],
        ["The organised sector generally follows formal employment rules.", "Workers and employers are covered by regulations and records."],
        ["The unorganised sector often provides less job security.", "Work may be irregular and legal protections may be weakly enforced."],
        ["GDP is a measure of production within a country over a period.", "It adds the value of final goods and services produced in a year."],
        ["Public services can be important even when they do not generate private profit.", "Education, health, and sanitation support wider social welfare."],
        ["The three sectors are independent of one another.", "Production often relies on inputs and services from other sectors."],
        ["Underemployment means a person has no work at all.", "Underemployment describes work that does not fully use a person's time or capacity."],
        ["Government can act to improve access to employment and services.", "Public programmes and services may address gaps in market provision."]
      ],
      completion: {
        conclusion: { paragraphs: ["This chapter organises economic activity into three sectors. The primary sector obtains products from nature, the secondary sector processes materials or builds, and the tertiary sector provides services. These are not separate islands: farms need transport and banking, factories need raw materials and communication, and services depend on households and businesses.", "GDP measures the value of final goods and services produced within a country in a year. Counting only final output avoids counting the same value repeatedly as a product moves through production. But GDP alone does not show whether work is secure or income fairly shared. Disguised unemployment is common when more people work on a task than are needed to produce the same output; underemployment also includes people whose skills or time are not fully used.", "The chapter distinguishes organised work, which is more formally recorded and regulated, from unorganised work, where protections are often weaker. It also compares public and private activity. Public services and employment programmes can help meet needs that markets do not serve equitably. For exams, define each sector, explain interdependence, distinguish GDP from employment quality, and give a clear example of underemployment."], takeaways: ["Primary activities use natural resources; secondary activities process; tertiary activities provide services.", "The three sectors depend on one another.", "GDP counts final goods and services to avoid double counting.", "Disguised unemployment means some workers are not needed for current output.", "Organised and unorganised sectors differ in regulation and job protection.", "Public services and programmes can support welfare and employment."] },
        wholeFlow: [{title:"CLASSIFY WORK",points:["Primary: obtain from nature","Secondary: process or build","Tertiary: provide services"]},{title:"CONNECT THE SECTORS",points:["Farm produces cotton","Factory turns cotton into cloth","Transport, banking, storage, and retail connect product to buyers"]},{title:"MEASURE OUTPUT",points:["Add final goods and services produced in a year","GDP avoids double counting intermediate goods"]},{title:"CHECK EMPLOYMENT",points:["Underemployment: work does not use all capacity","Disguised unemployment: some workers can leave with no output loss","Seasonal and insecure work can hide livelihood problems"]},{title:"COMPARE WORK CONDITIONS",points:["Organised sector: formal records and rules","Unorganised sector: weaker protection and irregular work"]},{title:"PUBLIC AND PRIVATE ROLES",points:["Private activity produces goods and services for markets","Public activity provides services and addresses wider needs"]},{title:"OUTCOME",points:["Study output, jobs, security, and access together"]}],
        visuals:[{kind:"network",title:"A cotton shirt crosses all three sectors",what:"A production chain from field to factory to shop.",shows:"Primary cotton growing supplies secondary textile production; transport and retail services belong to the tertiary sector.",importance:"A familiar product shows how sectors depend on one another.",remember:["Cotton farming is primary.","Cloth manufacturing is secondary.","Transport and retail are tertiary."],questions:["Classify cotton farming, cloth making, and selling the shirt.","Name one tertiary service needed before the shirt reaches a buyer."],source:"Sector-link diagram."},{kind:"factory",title:"Recognising disguised unemployment",what:"A farm-work comparison of output with different numbers of workers.",shows:"If fewer workers can produce the same harvest, some labour was not adding extra output.",importance:"It separates visible employment from adequate use of labour.",remember:["People may appear employed.","Output stays the same when excess workers leave.","This is disguised unemployment."],questions:["How can a farm have disguised unemployment?","What happens to output when surplus workers leave?"],source:"Employment concept diagram."}],
        places:[{name:"Rural India",location:"Across Indian states",connection:"Agriculture and seasonal employment",significance:"Agriculture is a major primary activity; seasonal work and underemployment affect rural livelihoods.",exam:"Use a farm example to explain disguised unemployment."},{name:"Indian towns and industrial centres",location:"Across India",connection:"Manufacturing and services",significance:"Factories, construction, transport, trade, and offices show how secondary and tertiary activities connect.",exam:"Give examples from at least two sectors and explain their link."}],
        peoplePlaces:[{person:"Farm worker",place:"Rural farm",event:"Seasonal agricultural production",contribution:"Grows or harvests crops in the primary sector.",impact:"Provides raw materials for food processing, trade, and services."},{person:"Factory worker",place:"Industrial workplace",event:"Processing raw materials",contribution:"Transforms primary goods into manufactured products.",impact:"Creates secondary-sector output and demand for transport and retail."}],
        memorySheet:{terms:["Primary → natural resources.","Secondary → manufacturing and construction.","Tertiary → services.","GDP → value of final output within a country in a year."],causes:["Seasonal work → underemployment.","Too many workers for current farm output → disguised unemployment.","Production chain → demand for services."],effects:["Counting final goods → avoids double counting.","Formal rules → greater protections in organised work.","Public services → wider access to essential needs."],differences:["Primary uses nature; secondary processes; tertiary provides services.","GDP measures output; it does not by itself measure job security.","Organised work is formally regulated; unorganised work often has weaker protection."],chain:["Classify work","Connect sectors","Count final output","Check job use","Compare work conditions","Public and private roles"]}
      }
    },
    {
      id: "economics-3", number: 3, title: "Money and Credit",
      description: "Trace money’s evolution, banks and deposits, formal and informal credit, and how loan terms shape borrowers’ lives.",
      topics: ["Barter and double coincidence", "Modern money", "Banks and deposits", "Formal and informal credit", "Self-help groups"],
      overview: "Money makes exchange easier than barter because people do not need to find someone who wants exactly what they offer. Modern money includes currency and bank deposits. Credit can help people invest or manage needs, but high interest and harsh conditions can create a debt trap. The chapter compares formal and informal lenders and introduces self-help groups.",
      fiveMinutes: "Barter requires a double coincidence of wants. Currency accepted by the public solves this problem. Bank deposits are also money because they can be withdrawn or used for payments, including cheques and digital transfers. Banks keep some deposits as cash and lend the rest. Credit is an agreement involving a loan, interest, collateral, and repayment terms. A loan can support production, but if income fails while interest accumulates, a borrower may fall into a debt trap. Banks and cooperatives are formal sources regulated by the Reserve Bank of India; moneylenders and traders are informal sources. Self-help groups help members save and access small loans.",
      people: ["Borrowers: households, farmers, and businesses who use credit for different purposes.", "Lenders: banks, cooperatives, moneylenders, traders, and self-help groups offering credit on different terms.", "Reserve Bank of India: the central bank that supervises formal banking institutions."],
      dates: ["1935: Reserve Bank of India begins operations.", "1969: major commercial banks are nationalised in India.", "1992: NABARD's Self-Help Group–Bank Linkage Programme begins."],
      events: ["Barter: exchange without money requires each trader to want what the other offers.", "Currency: widely accepted money makes exchange and payment simpler.", "Bank lending: banks use a portion of deposits to provide loans while retaining reserves.", "Credit terms: interest, collateral, and repayment schedules determine a loan's cost and risk.", "Self-help groups: members save regularly and provide or arrange small loans."],
      terms: ["Double coincidence of wants: each trader must want what the other is offering in barter.", "Demand deposit: bank money withdrawable on demand and usable for payments.", "Collateral: an asset pledged by a borrower as security for a loan.", "Formal credit: loans from regulated sources such as banks and cooperatives.", "Debt trap: a cycle where repayment difficulty leads to growing debt and further borrowing."],
      causesEffects: ["Cause: barter requires matching wants. Effect: trade is slow and limited.", "Cause: a productive loan with manageable terms. Effect: investment can raise income and support repayment.", "Cause: crop failure or low earnings with high-interest debt. Effect: repayment difficulty and a possible debt trap."],
      mnemonics: "Credit check: I-C-R = Interest, Collateral, Repayment terms. Compare all three before calling a loan helpful.",
      visual: { label: "From saving to borrowing", kind: "route", points: ["Household deposits", "Bank keeps reserves", "Bank lends", "Borrower invests and repays"] },
      story: ["A trader with grain needs shoes, but the shoemaker does not need grain: barter stalls.", "Accepted currency lets both traders sell and buy without matching wants directly.", "People deposit money in banks; banks keep reserves and lend part of the deposits.", "A loan can help a borrower invest, but the result depends on the loan terms and the income earned.", "The chapter compares fairer formal credit with informal credit and shows how groups can build access together."],
      simple: ["Barter means swapping one good for another, and finding a matching trader can be hard.", "Money is accepted by many people, so buying and selling is easier.", "Banks keep some deposited money and lend some to borrowers.", "A loan can help, but its interest and repayment rules matter.", "If earnings are too low to repay a loan, debt can keep growing."],
      simple: ["Barter is swapping goods directly, and it can be difficult to find the right trading partner.", "Money is accepted by many people, so buying and selling is easier.", "Banks take deposits and lend part of that money to borrowers.", "Credit can help, but interest and repayment rules matter a lot.", "A borrower may get trapped in debt if repayments grow faster than income."],
      summary: "Money solves barter's matching problem. Credit supports activity when loan terms are manageable, but can cause distress when repayment becomes impossible. Formal lenders are regulated; informal credit often carries higher costs. Self-help groups improve access for members.",
      oneMinute: ["Barter needs a double coincidence of wants.", "Currency and demand deposits are forms of modern money.", "Banks keep reserves and lend a portion of deposits.", "Interest, collateral, and repayment terms shape whether credit helps or harms."],
      assertionReasons: [
        ["Money removes the need for double coincidence in most exchanges.", "People accept money as a medium of exchange."],
        ["Demand deposits can function as money.", "They can be withdrawn and used to make payments."],
        ["Banks keep only part of their deposits as cash reserves.", "They lend a portion of deposits to borrowers."],
        ["Collateral reduces a lender's risk.", "A borrower pledges an asset that may be claimed if the loan is not repaid."],
        ["Credit can have positive or negative effects.", "The result depends on income, interest, and repayment terms."],
        ["Informal lenders are generally regulated like banks.", "Moneylenders and traders usually operate outside the same formal banking regulation."],
        ["A debt trap can begin when borrowers cannot meet loan repayments.", "Unpaid debt and interest may require further borrowing."],
        ["Self-help groups can improve access to small loans.", "Members save regularly and lend to one another or connect with banks."],
        ["Barter is always more efficient than money.", "Barter can fail when traders' wants do not match."],
        ["The Reserve Bank of India supervises formal banking institutions.", "It is India's central bank and regulates the formal monetary system."]
      ],
      completion: {
        conclusion: { paragraphs: ["Money developed to make exchange easier. In barter, two people must each want what the other offers at the same time, a double coincidence of wants. Currency accepted by the public avoids this difficulty. Bank deposits also serve as money because people can withdraw them or use them for payments.", "Banks accept deposits, keep a portion as reserves, and lend some deposits to borrowers. Credit allows households and producers to meet costs or invest before they have all the needed cash. A loan's effects depend on its terms: interest, collateral, repayment schedule, and the borrower's ability to earn. A productive loan can support income, while low returns, crop failure, or high interest can make repayment impossible and create a debt trap.", "Formal credit from banks and cooperatives is regulated and generally offers clearer terms; informal lenders may charge much higher interest or impose difficult conditions. Self-help groups build savings among members and can provide small loans or link borrowers to banks. For board answers, define the terms, compare credit sources, and explain both a positive and a negative outcome of credit."], takeaways: ["Barter requires a double coincidence of wants.", "Currency and demand deposits are modern forms of money.", "Banks keep reserves and lend a portion of deposits.", "Interest, collateral, and repayment schedule are key loan terms.", "Credit can support investment or cause a debt trap.", "Self-help groups promote saving and access to small loans."] },
        wholeFlow: [{title:"BARTER PROBLEM",points:["Goods exchanged directly","Each trader must want what the other offers","Double coincidence makes trade difficult"]},{title:"MONEY",points:["Currency is widely accepted","Demand deposits can be used for payment","Exchange becomes easier"]},{title:"BANKS AND CREDIT",points:["People deposit savings","Banks keep reserves","Banks lend a portion to borrowers"]},{title:"CHECK THE LOAN TERMS",points:["Interest rate","Collateral required","Repayment schedule"]},{title:"OUTCOME DEPENDS ON THE BORROWER",points:["Income-generating activity → repayment may be manageable","Low income or crop failure → repayment stress","High-cost borrowing → debt trap risk"]},{title:"CREDIT SOURCES",points:["Formal: banks and cooperatives, regulated","Informal: moneylenders and traders, often costlier","Self-help groups: savings and small loans"]},{title:"CONCLUSION",points:["Credit is useful when terms and repayment capacity are sound","Wider access to fair credit supports livelihoods"]}],
        visuals:[{kind:"network",title:"How bank deposits become loans",what:"A flow diagram linking savers, banks, and borrowers.",shows:"Deposits provide banks with funds; banks retain reserves and lend part to borrowers.",importance:"It explains why deposits and loans connect different people in the economy.",remember:["Deposits are liabilities for banks and assets for depositors.","Banks retain some cash reserves.","Loans must be repaid with interest."],questions:["How do deposits help banks provide credit?","Why do banks keep reserves rather than lend every deposit?"],source:"Banking flow diagram."},{kind:"routes",title:"Credit can help or harm",what:"A decision path comparing loan use, earnings, and repayment.",shows:"A productive loan may increase income; an unmanageable loan can lead to arrears and further borrowing.",importance:"The same act of borrowing can have different outcomes depending on terms and circumstances.",remember:["Check the purpose of the loan.","Compare interest and repayment terms.","Consider uncertain income and risks."],questions:["Give one example of credit helping a borrower.","Explain how a borrower may enter a debt trap."],source:"Credit-outcome diagram."}],
        places:[{name:"India",location:"National context",connection:"RBI, banks, cooperatives, and self-help groups",significance:"Formal credit institutions and community groups shape access to money and loans.",exam:"Distinguish formal from informal credit with examples."},{name:"Rural communities",location:"Across Indian states",connection:"Agricultural loans and self-help groups",significance:"Seasonal income and limited collateral can make fair credit access especially important.",exam:"Explain how a self-help group supports members who may lack bank access."}],
        peoplePlaces:[{person:"Self-help group member",place:"Local community",event:"Regular savings and group lending",contribution:"Saves with other members and may borrow from the group's pooled funds.",impact:"Builds access to small loans and can strengthen financial independence."}],
        memorySheet:{terms:["Double coincidence → both traders want each other's goods.","Demand deposit → money withdrawable from a bank on demand.","Collateral → asset pledged as loan security.","Debt trap → borrowing cycle caused by repayment difficulty."],causes:["Matching wants is difficult → money becomes useful.","Need for funds before income arrives → borrower seeks credit.","Low returns plus high interest → repayment stress."],effects:["Fair credit → can fund productive activity.","Costly informal loans → borrower pays more interest.","Self-help savings → members can access small loans."],differences:["Formal credit is regulated; informal credit is usually less regulated.","Credit helps when income can repay it; it harms when debt grows beyond repayment capacity."],chain:["Barter limits","Money accepted","Deposits collected","Loans made","Terms assessed","Income or debt outcome","Fair credit access"]}
      }
    },
    {
      id: "economics-4", number: 4, title: "Globalisation and the Indian Economy",
      description: "Explore how production, trade, foreign investment, technology, and policy changes connect India to the global economy.",
      topics: ["Multinational corporations", "Foreign investment", "Foreign trade", "Liberalisation", "WTO"],
      overview: "Globalisation is the growing connection between economies through trade, investment, technology, and movement of information. Multinational corporations organise production across countries. These links can create jobs and choices, but benefits and costs are not shared equally.",
      fiveMinutes: "A multinational corporation (MNC) owns or controls production in more than one country. It may invest directly, partner with local firms, or place orders with suppliers. Foreign trade connects markets and gives buyers more choice, while competition can pressure local producers. Since 1991 India has reduced some trade and investment barriers through liberalisation. The World Trade Organization promotes rules for international trade, but countries debate whether those rules are equally fair. Globalisation affects workers, firms, consumers, and regions differently.",
      people: ["MNCs: firms that own or control production in more than one country.", "Small producers and workers: groups that may gain access to larger markets but also face strong competition.", "Consumers: people whose choices and prices can change as imported and locally made goods compete.", "World Trade Organization: international body associated with rules for global trade."],
      dates: ["1991: India begins major economic liberalisation reforms.", "1995: World Trade Organization is established.", "2001: China joins the WTO."],
      events: ["MNC investment: firms locate production where skills, markets, infrastructure, and costs suit their plans.", "Foreign trade: goods cross borders, linking producers and buyers in different countries.", "Liberalisation: government reduces some restrictions on imports and foreign investment.", "Global supply chains: components and services may be produced in several countries.", "Uneven impacts: some producers expand while others struggle to compete."],
      terms: ["Globalisation: growing integration of economies through trade, investment, and technology.", "MNC: a company that owns or controls production in more than one country.", "Foreign investment: investment made by a company or individual in another country.", "Liberalisation: removal or reduction of government restrictions on trade and investment.", "WTO: World Trade Organization, which sets and oversees rules for international trade."],
      causesEffects: ["Cause: lower trade barriers and improved communication. Effect: firms coordinate production across borders more easily.", "Cause: MNC investment and global sourcing. Effect: new jobs and markets, alongside pressure on some local firms.", "Cause: international competition. Effect: consumers may gain choice while some workers face insecure work."],
      mnemonics: "Globalisation links T-I-T: Trade, Investment, Technology; ask who gains and who faces pressure.",
      visual: { label: "A product made across borders", kind: "route", points: ["MNC plans investment", "Parts sourced globally", "Production in locations", "Goods sold across markets"] },
      story: ["A company looks for workers, suppliers, and customers beyond one national border.", "Investment and trade connect production sites in different countries.", "New technology speeds communication and coordination across distance.", "Consumers may see more choice while local producers face new competition.", "Governments debate how to share gains fairly and protect workers and small producers."],
      simple: ["Globalisation means countries' economies are becoming more connected.", "A company may make different parts of one product in different countries.", "Trade and technology help goods, services, and information move across borders.", "Some people and businesses gain new opportunities; others face stronger competition.", "Rules, skills, and bargaining power affect who benefits."],
      simple: ["Globalisation means countries' economies are becoming more connected.", "Companies may make or assemble products in different countries.", "Trade and technology help goods, services, and information move across borders.", "Some businesses and consumers benefit, but some workers and small producers face pressure.", "The effects depend on rules, bargaining power, skills, and support for people affected."],
      summary: "Globalisation links countries through investment, trade, and technology. MNCs coordinate production across borders. Liberalisation increased India's integration after 1991, bringing new opportunities and uneven pressures that depend on bargaining power and policy.",
      oneMinute: ["MNCs own or control production in more than one country.", "Foreign trade links producers and consumers across borders.", "India's major liberalisation reforms begin in 1991.", "Globalisation creates opportunities and uneven effects."],
      assertionReasons: [
        ["MNCs can organise production in several countries.", "They choose locations based on markets, costs, skills, and infrastructure."],
        ["Foreign trade can connect producers and consumers in different countries.", "Goods cross national borders to be sold in new markets."],
        ["Globalisation can affect producers differently.", "Firms differ in size, resources, skills, and ability to compete."],
        ["Liberalisation can increase foreign trade and investment.", "Reducing restrictions makes some cross-border economic activity easier."],
        ["Consumers may gain more choice through global markets.", "Imported and locally produced goods can compete in the same market."],
        ["All workers benefit equally from globalisation.", "Workers' outcomes depend on skills, job security, and bargaining power."],
        ["Technology supports coordination across countries.", "Communication networks allow firms to share information quickly."],
        ["The WTO was established before India's 1991 reforms.", "The WTO began in 1995, after India's major 1991 reform period started."],
        ["Globalisation means only the movement of goods.", "It also includes investment, services, technology, and information."],
        ["Local firms may face increased competition when trade barriers fall.", "Foreign goods and companies may enter domestic markets more easily."]
      ],
      completion: {
        conclusion: { paragraphs: ["Globalisation describes the growing integration of economies through trade, foreign investment, technology, and information. Multinational corporations own or control production in more than one country. They may set up factories, partner with local companies, or place orders with local suppliers, connecting workers and producers to wider markets.", "Foreign trade allows products to move between countries and links buyers with producers elsewhere. Since 1991 India has reduced some barriers to trade and foreign investment through liberalisation. Communication and transport technologies make coordination across borders faster. The World Trade Organization, established in 1995, is associated with rules for international trade, though countries debate how fair those rules are in practice.", "Globalisation brings opportunities such as investment, jobs, access to markets, and more consumer choice. Its benefits are uneven: large firms may adapt more easily than small producers, and workers may face insecurity or pressure on wages. For exam answers, explain both sides, name the mechanisms (trade, investment, technology), and show how outcomes depend on bargaining power and government policy."], takeaways: ["MNCs own or control production in more than one country.", "Trade, investment, and technology drive economic integration.", "India's major liberalisation reforms begin in 1991.", "The WTO is established in 1995.", "Globalisation creates opportunities and pressures that are shared unevenly.", "Local producers and workers can need support to benefit fairly."] },
        wholeFlow: [{title:"CONNECTING ECONOMIES",points:["Trade moves goods and services","Investment moves capital","Technology moves information and coordination"]},{title:"MNC DECISIONS",points:["Choose sites, suppliers, and workers","Invest directly, partner, or place orders","Coordinate production across borders"]},{title:"FOREIGN TRADE",points:["Goods enter new markets","Buyers gain more choice","Domestic producers face competition"]},{title:"INDIA AND LIBERALISATION",points:["1991: reduce some trade and investment barriers","Greater foreign investment and trade links","WTO established in 1995"]},{title:"WHO GAINS?",points:["Some firms expand and add jobs","Consumers may gain choice and competitive prices","Small producers and workers may face pressure"]},{title:"OUTCOME",points:["Globalisation has uneven effects","Policies and bargaining power shape who benefits"]}],
        visuals:[{kind:"network",title:"A product made across borders",what:"A supply-chain diagram linking design, components, assembly, and sales across countries.",shows:"An MNC may coordinate different stages of one product in several locations.",importance:"It explains why a product's design, parts, assembly, and market can belong to different places.",remember:["MNCs coordinate production across countries.","Trade connects stages and markets.","Technology supports coordination."],questions:["How can one product involve several countries?","What factors might influence where an MNC locates production?"],source:"Global production flow diagram."},{kind:"factory",title:"Globalisation: opportunity and pressure",what:"A comparison of possible effects on firms, workers, and consumers.",shows:"Investment and competition can create jobs and choices while challenging less-resourced producers.",importance:"It helps avoid one-sided claims that globalisation benefits everyone or harms everyone equally.",remember:["Effects differ among groups.","Skills and bargaining power matter.","Policy can shape outcomes."],questions:["Name one possible benefit and one possible cost of globalisation.","Why may small producers experience global competition differently from MNCs?"],source:"Impact comparison diagram."}],
        places:[{name:"India",location:"South Asia",connection:"Liberalisation reforms from 1991",significance:"Policy changes reduced some restrictions on foreign trade and investment and increased integration with global markets.",exam:"Link 1991 reforms to increased trade and investment integration."},{name:"China",location:"East Asia",connection:"WTO membership in 2001",significance:"China's entry into the WTO is an example of growing participation in international trade rules.",exam:"Remember that China joined the WTO in 2001."}],
        peoplePlaces:[{person:"MNC",place:"Multiple countries",event:"Cross-border investment and production",contribution:"Owns or controls production in more than one country.",impact:"Connects suppliers, workers, consumers, and markets across borders."}],
        memorySheet:{terms:["Globalisation → growing integration across economies.","MNC → company controlling production in multiple countries.","Liberalisation → reducing restrictions on trade and investment.","Foreign investment → investment across national borders."],causes:["Communication technology → easier global coordination.","Lower trade barriers → more cross-border trade.","MNC investment → production links across locations."],effects:["New markets → possible jobs and sales.","More imports → consumer choice and competition.","Unequal resources → uneven benefits and pressures."],differences:["Foreign trade moves goods and services; foreign investment places capital in another country.","MNCs operate across countries; domestic firms may operate mainly within one country.","Globalisation creates possibilities, not equal outcomes for all."],chain:["Trade and technology","MNC decisions","Cross-border production","Liberalisation","Competition and opportunity","Uneven outcomes","Policy response"]}
      }
    },
    {
      id: "economics-5", number: 5, title: "Consumer Rights",
      description: "Learn why consumers need protection, how to make informed choices, and where to seek redress when goods or services fail.",
      topics: ["Consumer exploitation", "Consumer rights", "Consumer responsibilities", "Consumer courts", "COPRA"],
      overview: "Consumers can face adulteration, underweight goods, misleading claims, unsafe products, or poor service. Consumer protection laws and organisations provide rights and routes to redress. Informed choices, bills, labels, and complaints help consumers use those rights effectively.",
      fiveMinutes: "Consumers may be exploited when sellers hold more information or bargaining power. Common problems include adulteration, false weights, misleading advertisements, and unsafe goods. Consumer rights include safety, information, choice, being heard, redress, and consumer education. The Consumer Protection Act (COPRA) created a framework for complaint redress through consumer commissions. Consumers should check labels, expiry dates, prices, quality marks, and keep receipts. Rights work best when people know and use them responsibly.",
      people: ["Consumers: people who buy goods or use services and can seek information and redress.", "Consumer organisations: groups that spread awareness and help people make complaints.", "Consumer commissions: bodies that hear complaints and can order remedies under consumer law."],
      dates: ["1986: Consumer Protection Act (COPRA) enacted in India.", "2019: Consumer Protection Act updates and replaces the 1986 law.", "15 March: World Consumer Rights Day is observed internationally."],
      events: ["Consumer exploitation: poor quality, unsafe goods, false weights, or misleading claims harm buyers.", "Consumer movement: public pressure leads to laws and institutions for protection.", "Complaint redress: consumers can approach the appropriate consumer commission.", "Quality marks: labels such as ISI and AGMARK help identify standards in specified product categories.", "Consumer responsibility: checking information and keeping bills supports informed purchase and redress."],
      terms: ["Consumer: a person who buys goods or uses services for consideration.", "COPRA: Consumer Protection Act, the law providing a framework for consumer protection and redress.", "Redress: a remedy such as repair, replacement, refund, or compensation.", "Adulteration: lowering product quality by adding inferior or harmful substances.", "AGMARK: a quality certification mark used for certain agricultural products."],
      causesEffects: ["Cause: information imbalance and weak bargaining power. Effect: consumers may accept unsafe or overpriced goods.", "Cause: keeping a bill and product details. Effect: a consumer can better support a complaint.", "Cause: consumer awareness and legal protections. Effect: sellers face greater accountability."],
      mnemonics: "Before buying, remember L-B-Q: Label, Bill, Quality mark; then know your rights and where to complain.",
      visual: { label: "From purchase to redress", kind: "route", points: ["Check label and quality", "Keep bill and evidence", "Contact seller", "Seek consumer redress"] },
      story: ["A buyer sees an attractive advertisement but cannot tell whether the product is safe or fairly measured.", "Labels, quality marks, prices, and bills provide evidence for an informed decision.", "If a product is defective or a service fails, the consumer first raises the issue with the seller.", "Consumer protection law provides a path to complaint redress when the dispute is not resolved.", "Rights, awareness, and responsible choices together make markets more accountable."],
      simple: ["A consumer is someone who buys a product or uses a service.", "Sometimes a seller may hide information or sell unsafe or poor-quality goods.", "Consumer rights help people ask for safety, clear information, and a fair remedy.", "Read labels and keep the bill as proof of what you bought.", "If a seller will not fix the problem, you can make a consumer complaint."],
      simple: ["A consumer is someone who buys a product or uses a service.", "Sometimes sellers may hide information, use false weights, or sell unsafe goods.", "Consumer rights help people ask for safety, information, choice, and a remedy.", "Keep the bill and product details because they help prove what happened.", "If the seller does not fix the problem, a consumer commission can hear the complaint."],
      summary: "Consumer protection addresses unfair practices and information imbalance. Rights to safety, information, choice, hearing, redress, and education work alongside practical responsibilities such as checking labels and keeping receipts.",
      oneMinute: ["Consumers can face unsafe goods, false weights, and misleading claims.", "Rights include safety, information, choice, being heard, redress, and education.", "Keep bills and check labels, expiry dates, and quality marks.", "Consumer commissions provide routes to redress under consumer law."],
      assertionReasons: [
        ["Consumers need information to make informed choices.", "Labels and advertisements can affect how a product is understood."],
        ["A bill can help support a consumer complaint.", "It records purchase details and seller information."],
        ["The right to safety matters for hazardous goods and services.", "Unsafe products can cause injury or loss."],
        ["Consumer commissions provide a route for complaint redress.", "They can hear disputes and order remedies under consumer law."],
        ["A quality mark guarantees every product is perfect.", "Quality marks indicate specified standards and do not remove the need to inspect goods."],
        ["Consumer education can reduce exploitation.", "Informed consumers can check labels, prices, and terms."],
        ["Adulteration can harm consumers.", "Inferior or harmful substances may reduce safety and quality."],
        ["Consumers have responsibilities as well as rights.", "Checking details and keeping evidence supports fair transactions."],
        ["All complaints must be handled only by the seller.", "Consumer commissions can hear eligible disputes when issues remain unresolved."],
        ["Misleading advertisements can affect consumer decisions.", "Claims may create a false impression about quality or benefits."]
      ],
      completion: {
        conclusion: { paragraphs: ["This chapter explains why consumer protection is needed. Buyers may face adulteration, unsafe products, false weights, overcharging, misleading advertisements, or poor service. These problems grow when sellers know more than buyers or when consumers have little bargaining power. Consumer awareness and legal protections help rebalance that relationship.", "The chapter describes rights to safety, information, choice, being heard, redress, and consumer education. COPRA established a framework for complaint redress through consumer forums, now consumer commissions under updated law. Remedies can include repair, replacement, refund, or compensation, depending on the case. Quality marks such as ISI or AGMARK apply to specified product categories and help consumers identify standards.", "Consumers also have practical responsibilities: read labels and expiry dates, compare prices and quantities, check relevant quality marks, ask for a bill, and keep evidence. If a seller does not resolve a complaint, consumers can seek help from the appropriate commission or consumer organisation. For exams, identify the right involved, explain the unfair practice, and state a suitable remedy and evidence."], takeaways: ["Consumer exploitation can involve safety, quality, weight, price, or misleading information.", "Rights include safety, information, choice, being heard, redress, and education.", "Bills and labels help consumers make choices and support complaints.", "Consumer commissions provide a route to legal redress.", "Quality marks apply to specified products and standards.", "Consumer awareness and responsibilities strengthen consumer protection."] },
        wholeFlow: [{title:"WHY PROTECTION?",points:["Information and bargaining power may be unequal","Consumers may face unsafe goods, false weights, or misleading claims"]},{title:"KNOW YOUR RIGHTS",points:["Safety","Information and choice","Being heard and redress","Consumer education"]},{title:"BUY CAREFULLY",points:["Read label and expiry date","Check price, quantity, and relevant quality mark","Ask for and keep the bill"]},{title:"WHEN SOMETHING GOES WRONG",points:["Record the problem and keep evidence","Contact the seller or service provider","Approach the appropriate consumer commission if unresolved"]},{title:"POSSIBLE REMEDIES",points:["Repair or replacement","Refund or compensation","Correction of unfair practice"]},{title:"OUTCOME",points:["Informed consumers and enforceable rights encourage accountability"]}],
        visuals:[{kind:"newspaper",title:"Read a product label",what:"A checklist diagram highlighting product information a buyer can inspect.",shows:"Price, quantity, ingredients, dates, and quality marks help a consumer assess a product.",importance:"Information is a consumer right and a practical tool before purchase.",remember:["Check expiry and manufacturing dates.","Compare price and quantity.","Keep the bill after purchase."],questions:["Name three details to check on a packaged product.","How can a bill help if a product is defective?"],source:"Consumer label checklist."},{kind:"network",title:"Consumer complaint path",what:"A step-by-step route from identifying a problem to seeking redress.",shows:"Consumers preserve evidence, contact the seller, and can approach a consumer commission if unresolved.",importance:"A clear process turns consumer rights into practical action.",remember:["Keep receipts and records.","State the problem and remedy requested.","Use the appropriate commission."],questions:["What evidence should a consumer keep?","What can a consumer do if a seller refuses to address a complaint?"],source:"Complaint redress flow."}],
        places:[{name:"Consumer commissions",location:"District, state, and national levels in India",connection:"Consumer dispute redress",significance:"Consumer commissions hear eligible complaints and may order remedies under consumer protection law.",exam:"Explain the role of commissions in providing redress."},{name:"India",location:"National legal framework",connection:"Consumer Protection Acts of 1986 and 2019",significance:"Consumer laws provide rights and complaint mechanisms and have been updated as markets change.",exam:"Know COPRA and explain consumer rights and remedies."}],
        peoplePlaces:[{person:"Consumer",place:"Market and consumer commission",event:"Purchase, complaint, and redress",contribution:"Checks information, keeps evidence, and raises a complaint when treated unfairly.",impact:"Using rights can encourage sellers to meet standards and resolve disputes."}],
        memorySheet:{terms:["Consumer → buyer or service user.","Redress → repair, replacement, refund, or compensation.","Adulteration → adding inferior or harmful substances.","COPRA → Consumer Protection Act framework."],causes:["Information imbalance → risk of misleading sale.","Unsafe or defective goods → need for consumer protection.","Bill and evidence → stronger complaint."],effects:["Consumer awareness → better informed choices.","Commission remedy → possible repair, replacement, refund, or compensation.","Enforcement → greater seller accountability."],differences:["Right to information helps before purchase; right to redress helps after harm or dispute.","Quality marks indicate specified standards; they do not guarantee every aspect of a product."],chain:["Market risk","Know rights","Check label","Keep bill","Raise complaint","Seek redress","Improve accountability"]}
      }
    }
  ];

  const conceptsByChapter = {
    "economics-1": [
      { title: "Development goals differ", text: "People value goals according to their needs, work, and circumstances. Income, security, respect, equality, freedom, and a clean environment can all matter.", example: "A worker may prioritise secure employment while a family may prioritise a nearby school and clinic." },
      { title: "Income averages hide distribution", text: "Per capita income divides total income by population. It allows a broad comparison but cannot show how income is shared among people.", example: "Two countries can have the same average income but very different gaps between rich and poor." },
      { title: "Human development uses social indicators", text: "Health and education indicators add information about people's capabilities and opportunities that income alone cannot show.", example: "Life expectancy and literacy help compare quality of life alongside income." },
      { title: "Sustainability protects future choices", text: "Development is sustainable when present needs are met without exhausting resources or damaging the environment needed by future generations.", example: "Groundwater use should not continually exceed the rate at which aquifers recharge." }
    ],
    "economics-2": [
      { title: "Three sectors classify economic work", text: "The primary sector obtains natural products, the secondary sector processes materials, and the tertiary sector provides services.", example: "Cotton growing, cloth manufacturing, and transporting the cloth belong to primary, secondary, and tertiary activity." },
      { title: "GDP counts final output", text: "Gross Domestic Product adds the value of final goods and services produced within a country during a year, avoiding repeated counting of inputs.", example: "Count the final cloth value rather than adding cotton and cloth values as if they were unrelated products." },
      { title: "Underemployment hides unused labour", text: "People may appear to have work even when fewer workers could produce the same output; their labour is not fully used.", example: "A family farm may have more workers than are needed to maintain its current harvest." },
      { title: "Work conditions vary by sector", text: "Organised work is formally recorded and regulated, while unorganised workers often face irregular jobs and weaker protections.", example: "A worker with a written contract and regulated hours has protections that a casual daily worker may not." }
    ],
    "economics-3": [
      { title: "Money solves the barter matching problem", text: "Barter requires both traders to want what the other offers. Widely accepted money allows people to sell to one person and buy from another.", example: "A farmer can sell grain for money and later use that money to buy shoes." },
      { title: "Banks connect savers and borrowers", text: "Banks accept deposits, keep a portion as reserves, and lend part of the deposits to people or firms that need credit.", example: "Household savings can help fund a small business loan." },
      { title: "Loan terms shape the cost of credit", text: "Interest, collateral, and repayment timing determine how much a borrower owes and what happens if repayment fails.", example: "A loan with high interest and strict repayment can be risky when farm income is uncertain." },
      { title: "Credit can create opportunity or a debt trap", text: "A loan can raise income when it funds productive activity, but debt can grow when earnings are too low to meet repayments.", example: "A crop loan may help production, while crop failure can leave a farmer unable to repay." }
    ],
    "economics-4": [
      { title: "MNCs coordinate production across countries", text: "Multinational corporations own or control production in more than one country and choose locations based on markets, costs, skills, and infrastructure.", example: "A product can be designed in one country, assembled in another, and sold in many markets." },
      { title: "Trade links buyers and producers", text: "Foreign trade lets goods and services cross national borders, connecting producers to customers and competitors in other countries.", example: "Imported goods may offer consumers more choice while competing with local producers." },
      { title: "Technology speeds global coordination", text: "Communication and transport technologies make it easier for businesses to manage suppliers and production across long distances.", example: "A company can send design changes quickly to factories in several countries." },
      { title: "Globalisation has uneven effects", text: "Firms, workers, and consumers do not share gains and pressures equally; skills, resources, and bargaining power influence outcomes.", example: "A large supplier may gain a contract while a smaller producer struggles to match its costs." }
    ],
    "economics-5": [
      { title: "Information helps consumers choose", text: "Labels, prices, quantities, ingredients, expiry dates, and advertisements shape a buyer's decision. Missing or false information can enable exploitation.", example: "Checking the expiry date and unit price helps compare packaged goods." },
      { title: "Consumer rights provide protection", text: "Rights to safety, information, choice, being heard, redress, and education help consumers respond to unfair treatment.", example: "A buyer can seek a remedy for a defective product rather than simply accept the loss." },
      { title: "Evidence supports redress", text: "Bills, labels, warranty records, and complaint details help establish what was purchased and what went wrong.", example: "A purchase bill can connect the consumer, seller, product, and purchase date." },
      { title: "Consumer responsibility strengthens rights", text: "Reading product details, comparing terms, and keeping records help consumers make informed choices and support complaints.", example: "Keeping a receipt and packaging can help explain a product-quality complaint." }
    ]
  };

  subject.chapters = chapters;
  subject.status = "available";
  subject.bookTitle = "Understanding Economic Development";
  subject.description = "Understand development, work, money, global connections, and consumer choices through five Class 10 Economics chapters.";
  for (const chapter of chapters) {
    chapter.subjectId = subject.id;
    chapter.subjectName = subject.name;
    const enhancement = {
      concepts: conceptsByChapter[chapter.id],
      flowcharts: [{ style: "steps", title: chapter.visual.label, steps: chapter.visual.points }, { style: "branch", title: `Explore ${chapter.title}`, groups: [{ label: "Key ideas", items: chapter.topics.slice(0, 3) }, { label: "Connections", items: chapter.causesEffects.slice(0, 3) }] }],
      conceptMap: { center: chapter.title.toUpperCase(), branches: [{ label: "Key topics", items: chapter.topics.slice(0, 4) }, { label: "Terms", items: chapter.terms.slice(0, 4).map((item) => item.split(":")[0]) }, { label: "Outcomes", items: chapter.causesEffects.slice(0, 3).map((item) => item.split(".")[0]) }] },
      timeline: chapter.dates.map((item) => { const [date, event] = item.split(": "); return [date, event, chapter.events.find((entry) => entry.toLowerCase().includes(event.split(" ")[0].toLowerCase())) || chapter.summary, "Economics"] }),
      comparisons: [{ title: `${chapter.topics[0]}: key comparison`, columns: ["Idea", "Why it matters"], rows: chapter.terms.slice(0, 3).map((item) => { const [term, meaning] = item.split(": "); return [term, meaning] }) }],
      memory: [chapter.mnemonics, ...chapter.oneMinute.slice(0, 2)],
      confusion: chapter.terms.slice(0, 2).map((item, index) => ({ left: item.split(":")[0], right: chapter.terms[index + 2]?.split(":")[0] || chapter.topics[1], difference: `${item.split(": ").slice(1).join(": ")} Compare definitions carefully and use a chapter example.` })),
      exam: { remember: chapter.completion.conclusion.takeaways.slice(0, 3), concepts: chapter.topics.slice(0, 4), dates: chapter.dates, names: chapter.people, differences: chapter.completion.memorySheet.differences, short: `Explain one important concept from ${chapter.title}.`, long: `Describe the main ideas and their effects in ${chapter.title}.` },
      quick: { tenSeconds: chapter.summary, oneMinute: chapter.oneMinute, fiveMinutes: chapter.fiveMinutes, detailed: `${chapter.summary} ${chapter.causesEffects.join(" ")}` },
      assertionReasons: chapter.assertionReasons
    };
    chapter.enhanced = enhancement;
    chapter.completion.memorySheet.people = chapter.people;
    chapter.completion.memorySheet.dates = chapter.dates;
    chapter.completion.memorySheet.places = chapter.completion.places.map((place) => `${place.name} → ${place.significance}`);
    chapter.completion.memorySheet.mustRemember = [...chapter.completion.conclusion.takeaways, ...chapter.terms.slice(0, 6)].slice(0, 12);
    chapter.completionSectionCount = 28;
    enhancement.timeline.forEach(([date, event, description, topic]) => {
      window.LEARNING_DATA.timeline.push({ date: String(date), event, description, topic, chapterId: chapter.id, chapterTitle: chapter.title, subjectId: subject.id, subjectName: subject.name, important: true });
    });
  }
})();
