(function () {
  const chapters = {
    "history-1": {
      concepts: [
        { title: "From subject to citizen", text: "The French Revolution shifted political legitimacy from a monarch towards the nation and its citizens. New institutions, laws, and symbols helped make that shift visible.", example: "The tricolour and the idea of a uniform national community became public symbols of political change." },
        { title: "Liberalism: rights, with limits", text: "Liberals supported constitutional government, equality before law, and protection of private property. In practice, voting rights were often restricted by gender and property qualifications.", example: "The 1834 Zollverein reduced customs barriers between many German states, while Austria remained outside it." },
        { title: "Unification through different routes", text: "Italy's unification combined diplomacy and popular action. Prussia led German unification through state power, military conflict, and Bismarck's diplomacy.", example: "Cavour's alliance with France in 1859 helped weaken Austrian control in northern Italy." },
        { title: "Making a nation imaginable", text: "Artists personified nations as female allegories. Shared stories, folk culture, language, and symbols helped people imagine belonging to a larger community.", example: "Germania represented the German nation; Marianne became an emblem of France." }
      ],
      flowcharts: [
        { style: "horizontal", title: "The French Revolution's political shift", steps: ["Dynastic rule", "Popular sovereignty", "Citizenship and equal laws", "National symbols and institutions"] },
        { style: "branch", title: "Two routes to unification", groups: [{ label: "Italy", items: ["Mazzini's republican vision", "Cavour's diplomacy", "Garibaldi's campaigns", "Kingdom proclaimed, 1861"] }, { label: "Germany", items: ["Prussian leadership", "Bismarck's diplomacy", "Wars of unification", "Empire proclaimed, 1871"] }] },
        { style: "cycle", title: "How national identity took root", steps: ["Shared stories and culture", "A sense of belonging", "Political mobilisation", "New national institutions"] }
      ],
      conceptMap: { center: "NATIONALISM IN EUROPE", branches: [{ label: "Ideas", items: ["Citizenship", "Liberalism", "Popular sovereignty"] }, { label: "Movements", items: ["1848 revolutions", "Italian unification", "German unification"] }, { label: "Expressions", items: ["Flags and allegories", "Folk culture", "Shared language"] }] },
      timeline: [
        [1776, "American Declaration of Independence", "A declaration of popular sovereignty influenced later political debates.", "Ideas"],
        [1789, "French Revolution begins", "The revolution makes citizenship and the nation central political ideas.", "France"],
        [1797, "Napoleon invades Italy", "French control brings administrative changes as well as resistance.", "Italy"],
        [1815, "Congress of Vienna", "Conservative powers restore monarchies and redraw Europe's political map.", "Conservatism"],
        [1830, "July Revolution in France", "A revolution replaces the Bourbon monarch Charles X with Louis Philippe.", "Revolution"],
        [1831, "Young Italy is founded", "Mazzini organises a movement for a united Italian republic.", "Italy"],
        [1834, "Zollverein customs union", "Economic cooperation grows among many German states under Prussian leadership.", "Germany"],
        [1848, "Revolutions and Frankfurt Parliament", "Liberals and nationalists demand constitutions and a unified German nation.", "Revolution"],
        [1859, "War in northern Italy", "The Franco-Piedmontese alliance helps defeat Austrian forces in northern Italy.", "Italy"],
        [1861, "Kingdom of Italy proclaimed", "Victor Emmanuel II becomes king of a largely unified Italy.", "Italy"],
        [1866, "Austro-Prussian War", "Prussia defeats Austria and strengthens its leadership among German states.", "Germany"],
        [1870, "Franco-Prussian War begins", "The conflict helps draw southern German states behind Prussia.", "Germany"],
        [1871, "German Empire proclaimed", "The new empire is proclaimed at Versailles under Kaiser William I.", "Germany"]
      ],
      comparisons: [
        { title: "Italy and Germany: different routes", columns: ["Italy", "Germany"], rows: [["Piedmont-Sardinia was the leading state.", "Prussia was the leading state."], ["Cavour used diplomacy; Garibaldi led popular campaigns.", "Bismarck combined diplomacy with Prussian military power."], ["Kingdom proclaimed in 1861.", "German Empire proclaimed in 1871."]] },
        { title: "Liberalism: promise and limitation", columns: ["Principle", "Historical limitation"], rows: [["Equality before law", "Social and gender equality did not automatically follow."], ["Constitutional government", "Many people had no vote."], ["Political participation", "Property qualifications excluded poorer men in many settings."]] }
      ],
      memory: ["Name order: Ma-Ca-Ga = Mazzini imagined unity, Cavour negotiated, Garibaldi campaigned.", "Keep the unification anchors apart: Italy, 1861; German Empire, 1871.", "Congress of Vienna follows Napoleon's defeat: 1815 restores conservative power."],
      confusion: [{ left: "Nationalism", right: "Liberalism", difference: "Nationalism centres on a shared nation and political belonging; liberalism centres on individual rights, constitutional rule, and equality before law." }, { left: "Cavour", right: "Garibaldi", difference: "Cavour worked mainly through diplomacy as Piedmont-Sardinia's chief minister; Garibaldi led volunteer campaigns, especially in southern Italy." }, { left: "1848 Frankfurt Parliament", right: "1871 German Empire", difference: "The elected 1848 assembly's unity project failed; German unification was achieved under Prussian leadership in 1871." }],
      exam: { remember: ["Nationalism could unite people, but could also sharpen rivalry between nations.", "Liberal political rights in the nineteenth century did not mean universal suffrage.", "National identity was expressed through allegories, language, and folk culture."], concepts: ["The effects of the French Revolution on political identity.", "Compare the roles of Cavour, Garibaldi, Mazzini, and Bismarck.", "Explain why the Frankfurt Parliament failed and how German unification later proceeded."], dates: ["1815: Congress of Vienna", "1848: revolutions and Frankfurt Parliament", "1861: Kingdom of Italy", "1871: German Empire"], names: ["Mazzini: revolutionary republican vision", "Cavour: Piedmontese diplomacy", "Garibaldi: volunteer campaigns", "Bismarck: Prussian-led German unification"], differences: ["Italy and Germany", "Liberalism and nationalism", "The 1848 unity project and the 1871 empire"], short: "Explain the contribution of any two figures to Italian or German unification.", long: "Describe the process of German unification and explain the role of Prussia." },
      quick: { tenSeconds: "Nationalism reshaped Europe; Italy unified in 1861, Germany in 1871.", oneMinute: ["1789 spread citizenship and popular sovereignty.", "Vienna in 1815 restored conservative monarchies.", "1848 liberals demanded rights and unity; the Frankfurt project failed.", "Italy's route involved Cavour and Garibaldi; Germany's route was Prussian-led."], fiveMinutes: "Compare how Italy and Germany unified, then connect the French Revolution's ideas to the growth of national identity. Remember that liberalism promoted legal and constitutional rights, but political participation often remained restricted.", detailed: "Trace the shift from dynastic authority to citizenship; review the conservative settlement of 1815 and the revolutions of 1830 and 1848; compare Italian diplomacy and popular campaigns with Prussian state-led unification; explain how allegories and culture represented nations." }
    },
    "history-2": {
      concepts: [
        { title: "Satyagraha and non-violent resistance", text: "Satyagraha challenged injustice through truth, self-discipline, and non-violent action. It aimed to persuade as well as resist, and became one method within a broader freedom struggle.", example: "Gandhi's early campaigns in Champaran and Kheda addressed local grievances before nationwide movements." },
        { title: "From protest to non-cooperation", text: "The Rowlatt Act and the Jallianwala Bagh massacre deepened opposition to colonial rule. The Non-Cooperation movement asked people to withdraw support from selected colonial institutions.", example: "Students left government schools, lawyers gave up practice, and people boycotted foreign cloth in some places." },
        { title: "Why salt became a national symbol", text: "Salt was used by rich and poor alike, and the colonial salt law made an everyday necessity a powerful focus for protest. The march to Dandi turned a law-breaking act into a widely shared campaign.", example: "The march started at Sabarmati on 12 March 1930; Gandhi broke the salt law at Dandi on 6 April." },
        { title: "One movement, many expectations", text: "Peasants, business groups, workers, tribal communities, and women joined in different ways. They did not all share the same priorities, so nationalist unity involved negotiation and disagreement.", example: "Some peasants linked freedom to relief from rents, while business groups sought protection from foreign competition." }
      ],
      flowcharts: [
        { style: "horizontal", title: "How Civil Disobedience grew", steps: ["Salt law affects everyone", "Gandhi marches to Dandi", "Salt law openly broken", "Protest spreads to other laws"] },
        { style: "branch", title: "Different communities, different hopes", groups: [{ label: "Peasants", items: ["Relief from high rents", "Local agrarian demands"] }, { label: "Business groups", items: ["Protection from imports", "Support for Indian enterprise"] }, { label: "Women", items: ["Join marches and picketing", "Greater public participation"] }] },
        { style: "steps", title: "Rowlatt to Non-Cooperation", steps: ["Wartime hardships", "Rowlatt Act, 1919", "Jallianwala Bagh massacre", "Broader protest", "Non-Cooperation movement"] }
      ],
      conceptMap: { center: "INDIAN NATIONALISM", branches: [{ label: "Methods", items: ["Satyagraha", "Boycott", "Civil disobedience"] }, { label: "Movements", items: ["Non-Cooperation", "Khilafat alliance", "Salt March"] }, { label: "Participants", items: ["Peasants", "Workers", "Women", "Business groups"] }] },
      timeline: [
        [1915, "Gandhi returns to India", "After years in South Africa, Gandhi returns and becomes involved in Indian public life.", "Leadership"],
        [1917, "Champaran satyagraha", "A campaign challenges the hardships faced by indigo cultivators in Bihar.", "Satyagraha"],
        [1918, "Kheda satyagraha", "Peasants in Gujarat seek relief from revenue demands after crop failure.", "Satyagraha"],
        [1918, "Ahmedabad mill workers' strike", "Gandhi supports a labour dispute using a disciplined satyagraha approach.", "Workers"],
        [1919, "Rowlatt Act and satyagraha", "The repressive law prompts protests and a nationwide hartal.", "Protest"],
        [1919, "Jallianwala Bagh massacre", "British troops fire on an unarmed gathering in Amritsar on 13 April.", "Colonial violence"],
        [1920, "Non-Cooperation and Khilafat campaigns", "Congress and Khilafat leaders launch a broad programme of non-cooperation.", "Movement"],
        [1922, "Chauri Chaura and withdrawal", "After a violent incident at Chauri Chaura, Gandhi calls off Non-Cooperation.", "Turning point"],
        [1927, "Simon Commission appointed", "The all-British commission's appointment prompts opposition in India.", "Constitutional politics"],
        [1929, "Purna Swaraj declared", "At Lahore, Congress adopts complete independence as its goal in December.", "Independence"],
        [1930, "Salt March to Dandi", "Gandhi leads a march from Sabarmati; the salt law is broken on 6 April.", "Civil Disobedience"],
        [1931, "Gandhi-Irwin Pact", "The agreement pauses Civil Disobedience and enables Congress participation at the Round Table Conference.", "Negotiation"],
        [1932, "Poona Pact", "An agreement between Ambedkar and Gandhi addresses representation for the Depressed Classes.", "Representation"]
      ],
      comparisons: [
        { title: "Non-Cooperation and Civil Disobedience", columns: ["Non-Cooperation", "Civil Disobedience"], rows: [["Withdraw support from colonial institutions.", "Openly break selected colonial laws."], ["Boycott schools, courts, councils, and foreign goods.", "Break salt laws, refuse selected taxes, and defy regulations."], ["Launched in 1920; withdrawn after Chauri Chaura in 1922.", "Launched in 1930 after the Salt March; paused after the Gandhi-Irwin Pact."]] },
        { title: "Movement aims varied by group", columns: ["Participants", "Some important expectations"], rows: [["Rich peasants", "Relief from high revenue demands."], ["Business groups", "Reduced foreign competition and a stronger domestic market."], ["Dalit leaders", "Political safeguards and an end to social exclusion."], ["Women", "A larger public role, though political equality remained limited."]] }
      ],
      memory: ["Movement order: N-C = Non-Cooperation (1920), then Civil Disobedience (1930).", "Salt sequence: march begins 12 March; salt law broken at Dandi on 6 April 1930.", "Local starts: Champaran indigo (1917), Kheda crop and revenue (1918), Ahmedabad mill dispute (1918)."],
      confusion: [{ left: "Non-Cooperation", right: "Civil Disobedience", difference: "Non-Cooperation mainly withdraws support from colonial institutions; Civil Disobedience openly breaks selected colonial laws." }, { left: "Rowlatt Act", right: "Salt law", difference: "The 1919 Rowlatt Act allowed detention without trial; the colonial salt law controlled the production and sale of salt." }, { left: "1922", right: "1930", difference: "Non-Cooperation is withdrawn after Chauri Chaura in 1922; the Salt March launches Civil Disobedience in 1930." }],
      exam: { remember: ["Different social groups joined movements with different local aims.", "Gandhi withdrew Non-Cooperation after Chauri Chaura, where violence occurred.", "The Salt March connected an everyday commodity with colonial authority."], concepts: ["Explain why the salt law could unite diverse groups in protest.", "Compare Non-Cooperation with Civil Disobedience.", "Discuss the varied participation and expectations of social groups."], dates: ["1919: Rowlatt Act and Jallianwala Bagh", "1922: Chauri Chaura and withdrawal", "1929: Purna Swaraj adopted", "1930: Salt March", "1931: Gandhi-Irwin Pact"], names: ["Gandhi: satyagraha and mass mobilisation", "Nehru: complete independence", "Ambedkar: political representation and anti-caste struggle", "Alluri Sitarama Raju: Gudem Hills revolt"], differences: ["Non-Cooperation and Civil Disobedience", "Aims of peasants and business groups", "Nationalist unity and social justice"], short: "Why did Gandhi choose salt as a symbol for Civil Disobedience?", long: "Explain how different social groups participated in the Civil Disobedience movement and describe their expectations." },
      quick: { tenSeconds: "1919: repression; 1920: Non-Cooperation; 1930: Salt March and Civil Disobedience.", oneMinute: ["Champaran, Kheda, and Ahmedabad were early local campaigns.", "Rowlatt and Jallianwala Bagh intensified opposition.", "Non-Cooperation ended in 1922 after Chauri Chaura.", "Purna Swaraj in 1929 preceded the Salt March in 1930."], fiveMinutes: "Trace the shift from local satyagraha to nationwide movements. Compare boycott with law-breaking, then explain how salt and shared symbols brought people into protest while their economic and social aims remained diverse.", detailed: "Study the local campaigns of 1917-18, wartime discontent, the Rowlatt Act and Jallianwala Bagh, Non-Cooperation and its withdrawal, Purna Swaraj, the Salt March, Civil Disobedience, and the distinct aims of peasant, business, tribal, Dalit, and women's participation." }
    },
    "history-3": {
      concepts: [
        { title: "Global connections before modern industry", text: "Overland and maritime routes connected merchants and travellers long before modern globalisation. Goods travelled alongside religions, inventions, stories, and skills.", example: "Silk Routes linked parts of Asia, Europe, and North Africa through many branches rather than one road." },
        { title: "Empire, crops, and disease", text: "European expansion reshaped the Americas and global trade. The movement of crops affected diets, while conquest and diseases such as smallpox devastated Indigenous populations.", example: "The potato later became a staple in parts of Europe, while American silver entered long-distance trade." },
        { title: "Migration under indenture", text: "After slavery was formally abolished in the British Empire, plantation owners recruited workers from India under indenture. Contracts and recruitment practices could be coercive, and working conditions harsh.", example: "Indian indentured workers travelled to plantations in the Caribbean, Mauritius, Fiji, and elsewhere." },
        { title: "Interdependence and economic crisis", text: "Industrial production, finance, and trade linked economies more tightly. When demand and prices collapsed during the Great Depression, the effects travelled across these connections.", example: "Falling agricultural prices harmed producers who depended on export markets." }
      ],
      flowcharts: [
        { style: "horizontal", title: "How a trade connection works", steps: ["Demand for goods", "Trade routes and ships", "Movement of goods and capital", "New connections and dependencies"] },
        { style: "steps", title: "Why the Great Depression travelled", steps: ["Financial collapse", "Credit and demand shrink", "Trade and prices fall", "Jobs and incomes decline worldwide"] },
        { style: "branch", title: "Three flows across the global world", groups: [{ label: "Goods", items: ["Textiles and spices", "Food crops", "Industrial products"] }, { label: "People", items: ["Merchants and settlers", "Indentured labourers", "Refugees and migrants"] }, { label: "Ideas and capital", items: ["Religions and technologies", "Investment", "Economic policies"] }] }
      ],
      conceptMap: { center: "A CONNECTED GLOBAL WORLD", branches: [{ label: "What moves?", items: ["Goods", "People", "Capital", "Ideas"] }, { label: "What connects?", items: ["Trade routes", "Empire", "Transport", "Finance"] }, { label: "What follows?", items: ["Exchange", "Unequal power", "Migration", "Shared crises"] }] },
      timeline: [
        [1000, "Indian Ocean trade expands", "Merchants link East Africa, Arabia, India, and Southeast Asia in a changing maritime network.", "Premodern trade"],
        [1295, "Marco Polo returns to Venice", "Accounts of travel across Asia feed European interest in long-distance exchange.", "Travel"],
        [1492, "Columbus reaches the Americas", "Sustained European colonisation begins a profound reordering of the Americas.", "Conquest"],
        [1500, "American crops spread across oceans", "Crops such as potatoes and maize gradually alter diets in other regions.", "Food and exchange"],
        [1815, "Corn Laws introduced in Britain", "Protection of domestic grain interests shapes later debates about free trade.", "Trade policy"],
        [1840, "Corn Law debates intensify", "Arguments over protection and cheaper food form part of Britain's move toward freer trade.", "Trade policy"],
        [1845, "Irish Potato Famine begins", "Potato crop failure causes severe hunger and mass migration from Ireland.", "Migration"],
        [1846, "Britain repeals the Corn Laws", "The repeal signals a major move toward freer grain imports.", "Trade policy"],
        [1880, "Rinderpest spreads in Africa", "The cattle disease devastates herds, livelihoods, and food systems across much of the continent.", "Empire and ecology"],
        [1914, "First World War disrupts trade", "War transforms production, migration, and international economic relationships.", "War"],
        [1929, "Great Depression begins", "A financial crisis and steep fall in demand grow into a worldwide economic downturn.", "Economic crisis"],
        [1939, "Second World War begins", "Wartime economies reshape trade and production across the globe.", "War"],
        [1944, "Bretton Woods conference", "Representatives plan a post-war system for monetary cooperation and reconstruction.", "Institutions"],
        [1945, "Second World War ends", "Post-war reconstruction begins amid new international institutions.", "Reconstruction"]
      ],
      comparisons: [
        { title: "Premodern links and nineteenth-century globalisation", columns: ["Earlier connections", "Nineteenth-century expansion"], rows: [["Caravans and ships carried goods and ideas.", "Steamships, railways, and telegraphs accelerated movement."], ["Networks developed gradually through trading centres.", "Industrial production, capital, and imperial power reshaped trade."], ["Connections often followed established routes.", "Migration and commodity production expanded at a much larger scale."]] },
        { title: "Slavery and indentured labour", columns: ["Enslavement", "Indenture"], rows: [["People were treated as property and denied freedom.", "Workers signed fixed-term contracts, often under unequal and coercive conditions."], ["A violent system involving forced lifelong bondage.", "Contract terms did not guarantee fair treatment or freedom in practice."], ["Abolition occurred at different times in different places.", "Recruitment continued after abolition, particularly for plantation labour."]] }
      ],
      memory: ["Remember global flows as G-P-I: Goods, People, Ideas (and capital).", "The crisis chain: crash, credit tightens, commerce falls, workers suffer.", "Bretton Woods comes near the end of the Second World War: 1944."],
      confusion: [{ left: "Globalisation", right: "Free trade", difference: "Globalisation describes growing cross-border connections; free trade is a policy choice to reduce barriers such as tariffs." }, { left: "Slavery", right: "Indenture", difference: "Slavery denied legal freedom and treated people as property; indenture used fixed-term labour contracts, often made under coercive conditions." }, { left: "Bretton Woods conference", right: "Bretton Woods institutions", difference: "The 1944 conference agreed a framework; the IMF and World Bank were among the institutions established in its post-war system." }],
      exam: { remember: ["Global connections existed long before modern factories.", "Trade could connect regions while also reflecting unequal colonial power.", "The Depression spread through international trade, finance, and falling demand."], concepts: ["Explain how transport and technology changed global trade.", "Discuss the impact of indentured labour and the conditions of migration.", "Trace the causes and worldwide effects of the Great Depression."], dates: ["1492: Columbus reaches the Americas", "1845: Irish Potato Famine", "1880s: rinderpest in Africa", "1929: Great Depression", "1944: Bretton Woods conference"], names: ["Columbus: Atlantic voyage and European contact", "John Maynard Keynes: ideas influencing post-war economic planning", "Henry Ford: assembly-line production"], differences: ["Slavery and indenture", "Globalisation and free trade", "Premodern exchange and industrial-era networks"], short: "How did technology help create a more interconnected world?", long: "Explain how the Great Depression affected different parts of the world and why its effects spread." },
      quick: { tenSeconds: "Trade connected the world; empire and migration shaped it; the 1929 Depression exposed interdependence.", oneMinute: ["Long-distance routes carried ideas as well as goods.", "Conquest transformed the Americas and their populations.", "Indentured labour moved workers under restrictive contracts.", "The 1929 Depression spread through collapsing trade and demand; Bretton Woods met in 1944."], fiveMinutes: "Follow goods, people, capital, and ideas across trade routes and empires. Contrast voluntary exchange with coercion, then explain how economic links carried the Great Depression beyond its point of origin.", detailed: "Review premodern trade routes; the conquest of the Americas and crop exchange; nineteenth-century trade, migration, and indenture; colonial economic changes such as rinderpest; the Great Depression; and the Bretton Woods post-war framework." }
    },
    "history-4": {
      concepts: [
        { title: "Production before the factory", text: "Merchants organised production in rural households before factories expanded. This proto-industrial system connected artisans to wider markets without gathering every worker under one roof.", example: "A merchant could supply raw materials to rural families and collect finished goods for sale." },
        { title: "Why machines did not replace every worker", text: "Factories and machines grew, but hand production persisted. Skilled workers, seasonal demand, specialised goods, and changing markets could make manual production more suitable.", example: "Cloth for specialised buyers could still require hand weaving even when mills produced common fabrics." },
        { title: "Colonial power and Indian weavers", text: "Company agents called gomasthas supervised weavers and enforced delivery arrangements. British machine-made imports put additional pressure on Indian handloom producers.", example: "Weavers faced both reduced demand for some products and tighter control over access to raw cotton." },
        { title: "Industrial growth in India", text: "Indian entrepreneurs invested in mills, while merchants, labourers, and factory owners responded to changing markets. Industrial growth therefore followed local and colonial conditions as well as machine technology.", example: "Bombay cotton mills and Bengal jute mills emerged in the mid-nineteenth century." }
      ],
      flowcharts: [
        { style: "horizontal", title: "How the factory system reshaped production", steps: ["Machines and investment", "Workers gather at mills", "Tasks divided across stages", "Output and markets expand", "New labour conditions"] },
        { style: "branch", title: "Why hand production continued", groups: [{ label: "Markets", items: ["Seasonal demand", "Small production runs", "Customised goods"] }, { label: "Work", items: ["Specialised skills", "Flexible hours", "Low-cost labour"] }, { label: "Technology", items: ["Machines unevenly adopted", "Bottlenecks remained", "Handwork filled gaps"] }] },
        { style: "steps", title: "A weaver's changing position", steps: ["Company agent sets delivery", "Advance creates obligation", "Raw material and price controlled", "Debt and competition increase", "Weaver's choices narrow"] }
      ],
      conceptMap: { center: "INDUSTRIALISATION", branches: [{ label: "Production", items: ["Home work", "Workshops", "Factories"] }, { label: "Drivers", items: ["Markets", "Capital", "Machines", "Labour"] }, { label: "Effects", items: ["New jobs", "Unequal power", "Urban growth", "Changing skills"] }] },
      timeline: [
        [1733, "Flying shuttle patented", "John Kay's invention speeds up weaving and increases demand for yarn.", "Technology"],
        [1764, "Spinning jenny developed", "James Hargreaves's machine allows several threads to be spun at once.", "Technology"],
        [1769, "Water frame patented", "Richard Arkwright's water-powered spinning technology supports factory production.", "Technology"],
        [1779, "Spinning mule developed", "Samuel Crompton combines features of earlier spinning machines.", "Technology"],
        [1781, "Watt's steam engine patent", "Improved steam power can drive machinery beyond riverside locations.", "Power"],
        [1813, "Company's Indian trade monopoly restricted", "Charter changes expand the entry of British manufactured goods into Indian markets.", "Colonial trade"],
        [1830, "Railway era begins in Britain", "Railways help connect industrial producers with ports and markets.", "Transport"],
        [1854, "Cotton mill established in Bombay", "The mill marks an important early stage of India's modern cotton industry.", "India"],
        [1855, "Jute mill set up in Bengal", "The first jute mill at Rishra begins a new industrial sector.", "India"],
        [1861, "American Civil War begins", "The disruption of US cotton supplies raises demand for Indian raw cotton.", "Cotton trade"],
        [1865, "American Civil War ends", "US cotton returns to markets, affecting Indian cotton exporters and prices.", "Cotton trade"],
        [1905, "Swadeshi movement strengthens", "Boycott of foreign goods encourages interest in Indian-made products.", "Markets"]
      ],
      comparisons: [
        { title: "Hand production and factory production", columns: ["Hand and household work", "Factory work"], rows: [["Flexible pace and location.", "Work concentrated in a mill."], ["Skills and customisation may be important.", "Machines allow repeated, coordinated tasks."], ["Output can be slower or smaller in scale.", "Greater production capacity, but costly machinery and strict schedules."], ["Often continued alongside factories.", "Grew unevenly rather than replacing every handworker."]] },
        { title: "Proto-industrial and factory systems", columns: ["Proto-industrial system", "Factory system"], rows: [["Merchants coordinate production across homes.", "Owners gather workers and machinery in one workplace."], ["Artisans may retain some control over pace and craft.", "Hours and tasks are organised by the factory."], ["Production for wider markets before widespread factories.", "Mechanised production concentrated in mills."]] }
      ],
      memory: ["Machine sequence: Shuttle weaves; Jenny and Mule spin; Water Frame uses water power.", "India's early mills: cotton in Bombay 1854; jute in Bengal 1855.", "Remember the argument: factories grew, but handwork stayed."],
      confusion: [{ left: "Proto-industrialisation", right: "Factory system", difference: "Proto-industrial production was organised for markets but usually carried out in homes; factory production gathered workers and machinery in one site." }, { left: "Gomastha", right: "Jobber", difference: "A gomastha supervised weavers and company deliveries; a jobber recruited workers for factories." }, { left: "Spinning jenny", right: "Flying shuttle", difference: "The jenny increased spinning capacity; the flying shuttle improved weaving speed." }],
      exam: { remember: ["Industrialisation was gradual and uneven; hand production continued.", "Company agents shaped the working conditions of many Indian weavers.", "Markets, power, and labour were as important as the invention of a machine."], concepts: ["Explain proto-industrialisation and how the system operated.", "Compare hand production with factory production.", "Describe how colonial trade affected Indian weavers and industrial growth."], dates: ["1733: flying shuttle", "1764: spinning jenny", "1854: cotton mill in Bombay", "1855: jute mill in Bengal"], names: ["James Hargreaves: spinning jenny", "Richard Arkwright: water frame and factory system", "Dwarkanath Tagore and Jamsetjee Tata: Indian enterprise"], differences: ["Proto-industrial and factory systems", "Gomastha and jobber", "Spinning and weaving inventions"], short: "Why did hand labour continue even when machines and factories expanded?", long: "Explain how industrialisation affected Indian weavers, workers, and entrepreneurs." },
      quick: { tenSeconds: "Factories expanded, but handwork remained; colonial trade made Indian industry uneven.", oneMinute: ["Proto-industrial merchants organised work in rural homes.", "Machines increased some kinds of output but did not suit every market.", "Gomasthas supervised weavers for the Company.", "1854 Bombay cotton mill; 1855 Bengal jute mill."], fiveMinutes: "Compare home production, workshops, and mills. Explain why labour and machine adoption differed, then connect colonial imports and Company control to pressures on Indian weavers.", detailed: "Review proto-industrialisation; the main textile inventions; factory growth and the persistence of hand labour; Company control through gomasthas; Indian entrepreneurial investment; and the effects of trade, transport, and demand." }
    },
    "history-5": {
      concepts: [
        { title: "Printing begins with many traditions", text: "Woodblock printing developed in East Asia long before Gutenberg's European press. Different societies adapted printing to their languages, materials, readers, and institutions.", example: "The Diamond Sutra, printed in China in 868 CE, is a dated printed book." },
        { title: "From manuscripts to mass printing", text: "Movable type and presses increased the speed and volume of European book production. Print did not instantly replace manuscripts; readers and printers used both forms.", example: "Gutenberg's Bible, printed around 1455, demonstrates early European press production." },
        { title: "Print changes public debate", text: "Books, pamphlets, newspapers, and journals helped ideas circulate among broader reading publics. Print could support religious reform, social debate, and political criticism.", example: "Martin Luther's writings spread quickly through print after 1517." },
        { title: "Print in India and censorship", text: "Printing presses, vernacular publications, newspapers, and reform writing widened debate in India. Colonial authorities responded at times with censorship and press restrictions.", example: "The Vernacular Press Act of 1878 sought to control Indian-language publications." }
      ],
      flowcharts: [
        { style: "horizontal", title: "How printing widens debate", steps: ["Reusable printing technology", "More copies produced", "Books and newspapers circulate", "New readers encounter ideas", "Public debate grows"] },
        { style: "steps", title: "A printed idea travels", steps: ["Author writes", "Printer produces copies", "Booksellers and readers share", "Discussion and criticism spread", "Authorities may respond"] },
        { style: "branch", title: "Printing adapts to readers", groups: [{ label: "Formats", items: ["Books", "Pamphlets", "Newspapers", "Journals"] }, { label: "Audiences", items: ["Religious readers", "Reformers", "Women readers", "Political publics"] }, { label: "Responses", items: ["Debate", "Literacy", "Censorship", "New writing"] }] }
      ],
      conceptMap: { center: "PRINT CULTURE", branches: [{ label: "Technology", items: ["Woodblocks", "Movable type", "Presses"] }, { label: "Readers and texts", items: ["Books", "Newspapers", "Pamphlets", "Vernacular works"] }, { label: "Social effects", items: ["Reform", "Debate", "New publics", "Censorship"] }] },
      timeline: [
        [868, "Diamond Sutra printed in China", "The dated book is an important example of early East Asian woodblock printing.", "East Asia"],
        [1040, "Movable type developed in China", "Bi Sheng develops an early system of movable type using clay characters.", "Technology"],
        [1450, "Gutenberg's press developed in Europe", "Movable metal type and press methods help expand European book production.", "Europe"],
        [1455, "Gutenberg Bible printed", "An early major European book printed with movable metal type.", "Europe"],
        [1517, "Luther's Ninety-Five Theses", "Print helps Luther's criticism of Church practices circulate widely.", "Reformation"],
        [1556, "Printing press arrives in Goa", "Portuguese missionaries establish the first printing press in India.", "India"],
        [1780, "Hickey's Bengal Gazette", "James Augustus Hickey begins publishing an early English newspaper in India.", "Newspapers"],
        [1821, "Sambad Kaumudi begins", "Raja Rammohun Roy's Bengali weekly contributes to public and reform debate.", "Reform"],
        [1822, "Mirat-ul-Akhbar published", "Rammohun Roy's Persian journal participates in contemporary debate.", "Reform"],
        [1878, "Vernacular Press Act", "The colonial law enables controls on Indian-language newspapers.", "Censorship"],
        [1908, "Newspapers Incitement to Offences Act", "Colonial press restrictions tighten amid political opposition.", "Censorship"]
      ],
      comparisons: [
        { title: "Manuscripts and printed books", columns: ["Manuscripts", "Printed books"], rows: [["Copied by hand, one at a time.", "Many copies can be produced from type or blocks."], ["Time-consuming and often costly to reproduce.", "Printing can lower the cost and increase circulation."], ["Handwritten forms remain important for some readers and uses.", "Printed forms support wider reading and public discussion."]] },
        { title: "Traditional and new readers", columns: ["Established reading practices", "Expanding print publics"], rows: [["Reading may be associated with courtly, scholarly, or religious institutions.", "Newspapers, pamphlets, and cheap books reach more readers."], ["Manuscripts and oral reading remain significant.", "Print helps circulate debates beyond local settings."], ["Access to literacy is unequal.", "New readers include women, workers, and reform-minded audiences, though access varies."]] }
      ],
      memory: ["Print's broad route: East Asian woodblocks, European movable type, Indian presses and newspapers.", "Keep the India dates together: Goa 1556; Hickey 1780; Vernacular Press Act 1878.", "Technology spreads copies; readers spread debate; authorities may impose censorship."],
      confusion: [{ left: "Woodblock printing", right: "Movable type", difference: "Woodblock printing uses a carved block for a page; movable type arranges reusable characters to form text." }, { left: "Manuscript", right: "Printed book", difference: "A manuscript is written by hand; a printed book is reproduced using blocks or type, although both forms continued to exist." }, { left: "Hickey's Bengal Gazette", right: "Sambad Kaumudi", difference: "Hickey's Bengal Gazette was an English newspaper begun in 1780; Sambad Kaumudi was a Bengali weekly associated with Rammohun Roy from 1821." }],
      exam: { remember: ["East Asian printing traditions predate the European press.", "Print supports circulation but does not make every person literate or equally heard.", "Print could foster debate and reform while prompting censorship."], concepts: ["Explain how print changed religious and social debate.", "Describe the growth and role of print culture in India.", "Explain why colonial authorities tried to restrict vernacular newspapers."], dates: ["868: Diamond Sutra", "c. 1450: Gutenberg's press", "1556: press arrives in Goa", "1780: Bengal Gazette", "1878: Vernacular Press Act"], names: ["Gutenberg: European movable-type press", "Luther: reform writing spread in print", "Rammohun Roy: Bengali and Persian publications", "Hickey: early English newspaper in India"], differences: ["Woodblocks and movable type", "Manuscripts and printed texts", "English and vernacular newspapers"], short: "How did print help create a wider public for debate?", long: "Explain how print culture developed in India and discuss both its influence and the colonial response." },
      quick: { tenSeconds: "East Asian printing came first; print widened debate and also drew censorship.", oneMinute: ["868: Diamond Sutra in China.", "c. 1450: Gutenberg's European press.", "1556: first press in Goa; 1780: Bengal Gazette.", "1878: Vernacular Press Act restricts Indian-language newspapers."], fiveMinutes: "Trace the technology from East Asian woodblocks to movable type and Indian newspapers. Explain how cheaper copies widened discussion, then consider who could read and why governments tried to control the press.", detailed: "Review East Asian woodblock printing and movable type; Gutenberg and European print; print and the Reformation; the arrival of presses in India; newspapers and reform writing; new reading publics; and colonial censorship." }
    }
  };

  const timeline = [];
  for (const [chapterId, enhancement] of Object.entries(chapters)) {
    const chapter = window.LEARNING_DATA.findSubject("history").chapters.find((item) => item.id === chapterId);
    chapter.enhanced = enhancement;
    enhancement.timeline.forEach(([year, event, description, topic]) => {
      timeline.push({ date: String(year), event, description, topic, chapterId, chapterTitle: chapter.title, subjectId: "history", subjectName: "History", important: [1789, 1815, 1848, 1861, 1871, 1919, 1920, 1922, 1929, 1930, 1931, 1845, 1880, 1944, 1854, 1855, 1764, 1556, 1780, 1878].includes(year) });
    });
  }
  window.LEARNING_DATA.timeline.push(...timeline);
})();
